using System.ComponentModel;

namespace PoeBuilder.App.Services;

/// <summary>Application UI only. This is NOT a translation of PoE's game data.</summary>
public sealed class Localization : INotifyPropertyChanged
{
    private string _language = "ru";
    public string Language => _language;
    public event PropertyChangedEventHandler? PropertyChanged;
    public string this[string key] => Strings.TryGetValue(key, out var pair) ? (_language == "ru" ? pair.Ru : pair.En) : key;
    public void SetLanguage(string language)
    {
        if (language is not ("ru" or "en")) throw new ArgumentException("Unsupported UI language.");
        _language = language;
        PropertyChanged?.Invoke(this, new("Item[]"));
        PropertyChanged?.Invoke(this, new(nameof(Language)));
    }
    public string Format(string key, params object[] args) => string.Format(this[key], args);

    private static readonly Dictionary<string, (string Ru, string En)> Strings = new()
    {
        ["MainTree"]=("Основное дерево","Main tree"),
        ["Ascendancy"]=("Восхождение","Ascendancy"),
        ["AscendancyTree"]=("Мини-дерево восхождения","Ascendancy tree"),
        ["NoAscendancy"]=("Без восхождения","No ascendancy"),
        ["AscChangeQuestion"]=("Сменить восхождение? Узлы прежнего восхождения будут сброшены. Основное дерево останется. Действие можно отменить.","Change ascendancy? Previous ascendancy nodes will be cleared. The main tree is preserved. This can be undone."),
        ["TreeInvalidAscendancy"]=("Восхождение не соответствует классу или набору данных. План сохранён, редактирование заблокировано.","Ascendancy does not match this class or dataset. The plan is preserved; editing is blocked."),
        ["TreeClass"]=("Класс дерева","Tree class"),
        ["TreeAttribute"]=("Атрибут этого узла","This node’s attribute"),
        ["TreeAttributeStrength"]=("СИЛА","STRENGTH"),
        ["TreeAttributeDexterity"]=("ЛОВКОСТЬ","DEXTERITY"),
        ["TreeAttributeIntelligence"]=("ИНТЕЛЛЕКТ","INTELLIGENCE"),
        ["Apply"]=("Применить","Apply"),
        ["Undo"]=("Отменить шаг · Ctrl+Z","Undo · Ctrl+Z"),
        ["Redo"]=("Повторить шаг · Ctrl+Y","Redo · Ctrl+Y"),
        ["TreeDataNotice"]=("Данные GGG 0.5.5; соответствие 0.5.5c не подтверждено. ВНИМАНИЕ: русские игровые тексты пока не подключены — имена и свойства остаются EN даже при русском интерфейсе. Это незавершённая часть локализации.","GGG 0.5.5 data; equivalence to 0.5.5c is unverified. Russian game text is not yet connected: names and stats remain English even with Russian UI. Game localization is incomplete."),
        ["TreePointCounter"]=("{0} / {1}","{0} / {1}"),
        ["TreeWeaponSetLimit"]=("Лимит набора оружия — 24 очка.","Weapon set limit reached (24 points)."),
        ["TreeSearch"]=("ПОИСК УЗЛОВ · EN","FIND NODES · EN"),
        ["TreeSearchHint"]=("Имя, текст свойства или числовой ID. Поиск на английском.","Name, stat text or numeric ID. Search in English."),
        ["TreeSearchCount"]=("Найдено: {0} · в списке: {1}","Matches: {0} · listed: {1}"),
        ["TreeFocusClass"]=("К старту класса","Class start"),
        ["TreeFit"]=("Всё дерево","Fit tree"),
        ["TreeSelectNode"]=("Выбери узел","Select a node"),
        ["TreeInspectHint"]=("Как в игре: ЛКМ — взять узел (и путь к нему) в оба набора оружия, повторно — снять; Shift+ЛКМ — взять в 1-й набор оружия; Shift+ПКМ — во 2-й набор; ПКМ — только просмотр свойств и маршрута. При наведении сразу появляется рамка с названием и эффектами узла.", "As in the game: left click allocates the node (and its route) for both weapon sets and refunds it on a second click; Shift + left click takes it for weapon set I; Shift + right click for weapon set II; right click only inspects stats and the route. Hovering shows a framed panel with the node's name and what it does."),
        ["TreeTipAllocated"]=("Выбрано","Allocated"),
        ["TreeTipUnallocated"]=("Не выбрано","Not allocated"),
        ["TreeTipKeys"]=("УПРАВЛЕНИЕ","CONTROLS"),
        ["TreeTipKeyLeft"]=("ЛКМ — в оба набора оружия","Left click — both weapon sets"),
        ["TreeTipKeyShiftLeft"]=("Shift+ЛКМ — в 1-й набор оружия","Shift + left click — weapon set I"),
        ["TreeTipKeyShiftRight"]=("Shift+ПКМ — во 2-й набор оружия","Shift + right click — weapon set II"),
        ["TreeTipKeyRight"]=("ПКМ — только просмотр","Right click — inspect only"),
        ["TreeAllocatedWeaponSet"]=("Узел взят в набор оружия {0}.","Node allocated to weapon set {0}."),
        ["TreePanel"]=("Панель узла","Node panel"),
        ["TreePanelHint"]=("Показать или скрыть панель с поиском, описанием выбранного узла и набором оружия.","Show or hide the panel with the search box, the selected node and its weapon set."),
        ["TreeAllocate"]=("Выделить путь","Allocate path"),
        ["TreeRefund"]=("Снять узел / ветку","Refund node / branch"),
        ["TreeScope"]=("Основное дерево и отдельные графы восхождений. Лимиты очков раздельные и ручные; для восхождения начальное значение — 8. Безусловные бесплатные узлы не расходуют очки. Выборы внутри узлов, условные выделения, дополнительные очки и наборы оружия ещё заблокированы. Эффекты узлов входят в экран «Персонаж» (безусловные статы).","Main tree and separate ascendancy graphs. Point limits are separate and manual; the initial ascendancy limit is 8. Unconditional free nodes cost no points. Multiple-choice nodes, conditional allocations, extra points and weapon sets remain blocked. Node effects feed the Character sheet (unconditional stats)."),
        ["TreeBrowseOnly"]=("Режим просмотра. Создай или открой билд, чтобы выбрать класс и сохранять дерево.","Browse mode. Create or open a build to choose a class and save a tree plan."),
        ["TreeResetPlan"]=("Очистить план дерева…","Clear tree plan…"),
        ["TreeResetQuestion"]=("Очистить план дерева? Основное дерево и восхождение будут сброшены. Метаданные и заметки останутся. Действие можно отменить.","Clear the tree plan? Main allocations and ascendancy will be reset. Metadata and notes remain. This can be undone."),
        ["TreeChangeClassQuestion"]=("Смена класса очистит основное дерево и восхождение. Продолжить? Действие можно отменить.","Changing class clears the main tree and ascendancy. Continue? This can be undone."),
        ["TreeRefundQuestion"]=("Будет снято узлов: {0}, включая ветки, которые потеряют связь со стартом. Продолжить?","Refund {0} nodes, including branches that would lose their connection to the start?"),
        ["TreeDatasetMismatch"]=("План использует другой набор данных. Изменение дерева заблокировано; исходный план сохранён. Можно явно очистить дерево.","This plan uses a different dataset. Editing is blocked; the original plan is preserved. You can explicitly clear the tree."),
        ["TreeInvalidClass"]=("Этот класс недоступен в подключённом наборе. План не изменён.","This class is unavailable in the loaded dataset. The plan has not been changed."),
        ["TreeInvalidSaved"]=("План содержит отсутствующие или неподдерживаемые узлы. Изменение заблокировано; данные сохранены.","This plan contains missing or unsupported nodes. Editing is blocked; data is preserved."),
        ["TreeRepaired"]=("Сохранённое дерево приведено к правилам движка: {0} узл(ов) выдаёт предмет (анойнт или самоцвет) — они переведены в выданные и не тратят очки, {1} убрано (закреплённое дерево их не знает или больше не поддерживает), выбор атрибута по умолчанию добавлен у {2} узл(ов).","The saved tree was brought back to the engine's rules: {0} node(s) an item grants (an anoint or a jewel) moved into the granted set and cost no points, {1} given up (the pinned tree does not have them or no longer supports them), and {2} node(s) got the default attribute choice."),
        ["TreeOverBudget"]=("Недостаточно очков по заданному вручную лимиту.","This exceeds the manually configured point limit."),
        ["TreeInvalidAttribute"]=("Недопустимый выбор атрибута. План не изменён.","Invalid attribute selection. The plan has not been changed."),
        ["TreeDisconnected"]=("В плане есть узлы без связи со стартом класса. Изменение заблокировано.","The plan contains nodes disconnected from its class start. Editing is blocked."),
        ["TreeUnsupported"]=("Узел недоступен: специальная механика, условие, выбор варианта или чужой старт.","Unavailable node: special mechanic, condition, multiple-choice option or another class start."),
        ["TreeNoPath"]=("Нет доступного пути через поддерживаемые узлы.","No route exists through supported nodes."),
        ["TreeInvalidLimit"]=("Введите целое число от 0 до 10000. 0 — без ручного лимита.","Enter a whole number from 0 to 10000. 0 means no manual limit."),
        ["TreeStartInfo"]=("Старт выбранного класса. Не расходует очки и не снимается.","Selected class start. Costs no points and cannot be refunded."),
        ["TreeJewelInfo"]=("Гнездо выделено. Самоцвет можно установить на вкладке «Самоцветы»; эффекты радиуса и уникальные механики пока ограничены.","Socket allocated. Equip a jewel on the Jewels tab; radius effects and unique mechanics remain limited."),
        ["TreeAllocated"]=("Узел выделен.","Node allocated."),
        ["TreeRefunded"]=("Снято узлов: {0}.","Refunded {0} node(s)."),
        ["TreePathCost"]=("Кратчайший путь: +{0} очк.","Shortest path: +{0} points."),
        ["TreeLocked"]=("недоступно","unavailable"),
        ["TreeLoadFailed"]=("Не удалось загрузить проверенный набор дерева. Билды не изменены.","Could not load the verified tree dataset. Builds were not modified."),
        ["TreeAtlasFailed"]=("Не удалось загрузить иконки дерева. Узлы показаны без иконок.","Tree icons could not be loaded. Nodes are shown without icons."),
        ["Workspace"]=("РАБОЧЕЕ ПРОСТРАНСТВО","WORKSPACE"),
        ["Builds"]=("Мои билды","My builds"), ["Tree"]=("Дерево навыков","Passive tree"),
        ["Skills"]=("Умения","Skills"), ["Items"]=("Снаряжение","Equipment"),
        ["Configuration"]=("Конфигурация","Configuration"), ["Calculations"]=("Расчёты","Calculations"),
        ["Notes"]=("Заметки","Notes"), ["Settings"]=("Настройки","Settings"),
        ["RegEx"]=("Регекс","RegEx"),
        ["Independent"]=("Независимый проект · C# / WPF","Independent project · C# / WPF"),
        ["Alpha"]=("РАСЧЁТЫ · АЛЬФА (v1)","CALCULATIONS · ALPHA (v1)"),
        ["Save"]=("Сохранить","Save"), ["Import"]=("Импорт","Import"), ["Export"]=("Экспорт","Export"),
        ["ProgressionStages"]=("ЭТАПЫ","STAGES"), ["AddStage"]=("Добавить этап","Add stage"),
        ["RenameStage"]=("Переименовать этап","Rename stage"), ["DeleteStage"]=("Удалить этап","Delete stage"),
        ["StageNamePrompt"]=("Название этапа прокачки","Progression stage name"),
        ["StageDefaultNew"]=("Новый этап","New stage"),
        ["StageNameConflict"]=("Укажите уникальное название длиной до 40 символов.","Choose a unique name up to 40 characters."),
        ["StageAdded"]=("Добавлен этап: {0}","Added stage: {0}"),
        ["StageDeleted"]=("Этап удалён","Stage deleted"),
        ["DeleteStageQuestion"]=("Удалить выбранный этап прокачки? Его состояние будет потеряно.","Delete the selected progression stage? Its state will be lost."),
        ["NewBuild"]=("Новый билд","New build"), ["CreateBuild"]=("Создать билд","Create build"),
        ["HeroBadge"]=("PATH OF EXILE 2  /  НЕОФИЦИАЛЬНЫЙ ПЛАНИРОВЩИК","PATH OF EXILE 2  /  UNOFFICIAL BUILD PLANNER"),
        ["HeroTitle"]=("Каждый билд\nначинается с идеи.","Every build\nbegins with an idea."),
        ["HeroDescription"]=("Своё пространство для персонажей, планов и экспериментов.","Your own space for characters, plans and experiments."),
        ["Library"]=("Библиотека билдов","Build library"),
        ["SearchHint"]=("Поиск по названию и классу…","Search by name or class…"),
        ["LibrarySubtitle"]=("Локальное хранение. Твои идеи остаются у тебя.","Stored locally. Your ideas stay with you."),
        ["EmptyLibrary"]=("Здесь появятся твои билды","Your builds will appear here"),
        ["EmptyLibraryText"]=("Создай первый билд или импортируй файл PoeBuilder Native.","Create your first build or import a PoeBuilder Native file."),
        ["NoResults"]=("По этому запросу ничего не найдено","No builds match this search"),
        ["OpenBuild"]=("Открыть","Open"), ["Duplicate"]=("Копия","Duplicate"), ["Delete"]=("Удалить","Delete"),
        ["Level"]=("Уровень","Level"), ["UnspecifiedClass"]=("Класс не указан","Class not specified"),
        ["CurrentBuild"]=("ТЕКУЩИЙ БИЛД","CURRENT BUILD"), ["NoBuild"]=("Билд не выбран","No build selected"),
        ["Saved"]=("Сохранено локально","Saved locally"), ["Unsaved"]=("Есть изменения","Unsaved changes"),
        ["Draft"]=("Новый черновик","New draft"),
        ["Name"]=("Название билда","Build name"), ["Class"]=("Класс / персонаж","Class / character"),
        ["ClassHint"]=("Свободная подпись. Игровой класс выбирается в дереве.","Free-text label. Select the game class on the tree page."),
        ["TargetVersion"]=("Целевая версия игры","Target game version"),
        ["VersionHint"]=("Метка проекта. Не подтверждает поддержку механик патча.","A project label. It does not imply support for that patch's mechanics."),
        ["Profile"]=("Параметры персонажа","Character profile"),
        ["ProfileSubtitle"]=("Метаданные билда уже сохраняются. Игровые модификаторы будут подключены отдельно.","Build metadata is persisted. Game modifiers will be connected separately."),
        ["NoBuildText"]=("Сначала создай или открой билд в библиотеке.","Create or open a build from the library first."),
        ["DataMissing"]=("Игровые данные ещё не подключены","Game data is not connected yet"),
        ["DataBadge"]=("НЕТ НАБОРА ДАННЫХ","NO DATASET"),
        ["TreeText"]=("Это рабочее поле будущего редактора, а не дерево PoE 2.\nУзлы появятся после подключения проверенных игровых данных.","This is the future editor's workspace, not the PoE 2 tree.\nNodes will appear after verified game data is connected."),
        ["TreeControls"]=("Колесо — масштаб · Перетаскивание — обзор · Щелчок по узлу — выделить / снять (с путём, как в игре) · Shift+щелчок — просмотр маршрута · Enter — выделить · Delete — снять · Ctrl+Z / Ctrl+Y — история (при фокусе на дереве)","Wheel: zoom · Drag: pan · Click a node: allocate / refund (with its route, like the game) · Shift-click: inspect the route · Enter: allocate · Delete: refund · Ctrl+Z / Ctrl+Y: history (with tree focused)"),
        ["ResetView"]=("По центру","Reset view"),
        ["ZoomIn"]=("Увеличить","Zoom in"), ["ZoomOut"]=("Уменьшить","Zoom out"),
        ["SkillsTitle"]=("Собери свою связку умений","Plan your skill setup"),
        ["SkillsText"]=("Редактор групп активных умений и поддержек уже подключён. Уровни и качество импортируются; поддержками и совместимостью пока управляет ограниченный v1-калькулятор.","The active-skill and support-group editor is connected. Levels and quality are imported; support effects and compatibility remain limited in the v1 calculator."),
        ["ItemsTitle"]=("Снаряжение без компромиссов","Make every equipment choice count"),
        ["ItemsText"]=("Каталог баз, модификаторов, гнёзд и вставок подключён. Импорт PoB сохраняет поддерживаемые предметы, а неизвестные строки показывает в отчёте.","Base items, modifiers, sockets and socketables are connected. PoB import preserves supported items and reports unknown lines."),
        ["CalcsTitle"]=("Прозрачные расчёты","Transparent calculations"),
        ["CalcsText"]=("Экран персонажа показывает расчёты v1 по закреплённым данным и явно перечисляет допущения. Полный PoB combat pipeline, условия врага и часть механик пока не подключены.","The Character sheet shows v1 calculations over pinned data and lists its assumptions. The full PoB combat pipeline, enemy conditions and some mechanics are not connected yet."),
        ["Damage"]=("УРОН В СЕКУНДУ","DAMAGE PER SECOND"), ["Defence"]=("ВЫЖИВАЕМОСТЬ","SURVIVABILITY"),
        ["Resources"]=("РЕСУРСЫ","RESOURCES"), ["NotCalculated"]=("Не рассчитано","Not calculated"),
        ["NotesTitle"]=("Заметки к билду","Build notes"),
        ["NotesSubtitle"]=("План прокачки, дерево, экипировка и советы по своему билду.","Leveling plan, passive tree, equipment and advice for this build."),
        ["NotesHint"]=("Заметки сохраняются вместе с билдом. Ctrl+S — сохранить.","Notes are saved with the build. Press Ctrl+S to save."),
        ["NotesEditorLabel"]=("ЖУРНАЛ БИЛДА","BUILD JOURNAL"),
        ["NotesSections"]=("БЫСТРАЯ ВСТАВКА","QUICK SECTIONS"),
        ["NotesActSection"]=("Прокачка по актам","Leveling by acts"),
        ["NotesTreeSection"]=("Дерево пассивок","Passive tree"),
        ["NotesSkillsSection"]=("Умения и камни","Skills and gems"),
        ["NotesGearSection"]=("Снаряжение и апгрейды","Equipment and upgrades"),
        ["NotesTipsSection"]=("Советы и заметки","Tips and notes"),
        ["NotesEmpty"]=("Запиши здесь план прокачки, важные переходы и подсказки к билду…","Write your leveling plan, key transitions and build tips here…"),
        ["NotesCountLabel"]=("СИМВОЛОВ","CHARACTERS"),
        ["NotesBold"]=("Жирный","Bold"), ["NotesItalic"]=("Курсив","Italic"),
        ["NotesColorGold"]=("Золотой","Gold"), ["NotesColorCoral"]=("Коралловый","Coral"),
        ["NotesColorSky"]=("Голубой","Sky blue"), ["NotesColorGreen"]=("Зелёный","Green"),
        ["NotesColorText"]=("Обычный цвет","Default text color"),
        ["Appearance"]=("Интерфейс","Interface"), ["Language"]=("Язык приложения","Application language"),
        ["LanguageText"]=("Применяется сразу, без перезапуска.","Applied immediately. No restart required."),
        ["LocaleNotice"]=("Этот переключатель переводит интерфейс PoeBuilder. Официальные русские названия и описания из игры ещё не подключены.","This switch localizes the PoeBuilder interface. Official Russian game names and descriptions are not connected yet."),
        ["Storage"]=("Локальные данные","Local data"), ["OpenFolder"]=("Открыть папку","Open folder"),
        ["StorageText"]=("Билды и настройки хранятся отдельно от старого проекта и оригинального PoB. Облачной синхронизации и отправки данных нет.","Builds and settings are separate from the old project and original PoB. No cloud sync or data transmission."),
        ["ProjectStatus"]=("Статус проекта","Project status"),
        ["ProjectStatusText"]=("Собственный C# / WPF проект без PoB, Lua и SimpleGraphic. Уже работают библиотека билдов, дерево, восхождения, снаряжение, умения, импорт PoB и расчёты v1. Полный PoB-паритет, русский игровой текст и условные combat mechanics ещё не заявляются.","Independent C# / WPF project without PoB, Lua or SimpleGraphic. Build library, tree, ascendancies, equipment, skills, PoB import and v1 calculations are connected. Full PoB parity, Russian game text and conditional combat mechanics are not claimed yet."),
        ["Ready"]=("Готово","Ready"), ["Loading"]=("Загрузка…","Loading…"),
        ["SavedStatus"]=("Билд сохранён: {0}","Build saved: {0}"),
        ["ImportedStatus"]=("Импортирована новая копия: {0}","Imported a new copy: {0}"),
        ["ExportedStatus"]=("Файл билда экспортирован","Build file exported"),
        ["DeletedStatus"]=("Билд перемещён в локальную корзину","Build moved to local trash"),
        ["SkippedFiles"]=("Не прочитано файлов: {0}. Они не изменены.","Unreadable files: {0}. They were left unchanged."),
        ["SettingsRecovered"]=("Настройки не прочитаны. Использованы стандартные значения.","Settings could not be read. Defaults were used."),
        ["Error"]=("Не удалось выполнить действие","The action could not be completed"),
        ["ErrorText"]=("Изменения в редакторе не сброшены. Технические подробности:","Your editor changes were not discarded. Technical details:"),
        ["Confirm"]=("PoeBuilder — подтверждение","PoeBuilder — confirmation"),
        ["UnsavedQuestion"]=("Сохранить изменения в текущем билде?\n\nДа — сохранить. Нет — отбросить. Отмена — остаться.","Save changes to the current build?\n\nYes: save. No: discard. Cancel: stay here."),
        ["DeleteQuestion"]=("Переместить «{0}» в локальную корзину?\nФайл останется в подпапке Builds\\Trash.","Move “{0}” to local trash?\nThe file will remain in Builds\\Trash."),
        ["NameError"]=("Укажи название от 1 до 80 символов и уровень от 1 до 100.","Enter a name of 1–80 characters and a level from 1 to 100."),
        ["CopyName"]=("{0} — копия","{0} — copy"), ["NewName"]=("Мой новый билд","My new build"),
        ["NativeFilter"]=("Билд PoeBuilder Native (*.poebuild)|*.poebuild","PoeBuilder Native build (*.poebuild)|*.poebuild"),
        ["ImportTitle"]=("Импорт файла PoeBuilder Native — не кода PoB","Import a PoeBuilder Native file — not a PoB code"),
        ["Close"]=("Закрыть","Close"), ["Minimize"]=("Свернуть","Minimize"), ["Maximize"]=("Развернуть / восстановить","Maximize / restore"),
        ["BuildCount"]=("Билдов: {0}","Builds: {0}"),
        ["FoundationNotice"]=("Работают библиотека, заметки, RU/EN интерфейс, дерево и восхождения GGG 0.5.5, снаряжение и умения (каталог RePoE 4.5.5.2 EN, иконки GGG), расчёты v1 на экране «Персонаж».","Library, notes, RU/EN UI, GGG 0.5.5 tree and ascendancies, equipment and skills (RePoE 4.5.5.2 EN catalog, GGG icons), v1 calculations on the Character page."),
    
        ["CatalogMissing"]=("Каталог предметов и умений не загружен. Проверь установку: нужен файл Data\\Game\\catalog.json.","The equipment/skill catalog failed to load. Check the install: Data\\Game\\catalog.json is required."),
        ["GameDataNotice"]=("Каталог: сторонний снимок RePoE PoE2 4.5.5.2 (EN). Соответствие патчу 0.5.5c не подтверждено; игровые тексты остаются английскими.","Catalog: third-party RePoE PoE2 snapshot 4.5.5.2 (EN). Equivalence to patch 0.5.5c is unverified; game text remains English."),
        ["EquipmentScope"]=("Слоты в духе инвентаря. Нажатие открывает редактор: база, модификаторы из пула базы, качество, гнёзда с рунами, ядрами и идолами. Уникальные предметы, крафт и импорт из игры — позже. Итоги — на странице «Персонаж» (урон, защита, сопротивления).","Inventory-style slots. Clicking a slot opens the editor: base, mods from that base’s pool, quality, sockets with runes, cores and idols. Uniques, crafting and game import come later. Totals live on the Character page (damage, defence, resistances)."),
        ["SkillsScope"]=("Группы: активное умение или дух + до 5 поддержек, уровень и качество. Рекомендации — подсказка каталога, не проверка совместимости. Урон считается на экране «Персонаж»; поддержки пока не усиливают его.","Groups: one active or spirit skill plus up to 5 supports, with level and quality. Recommendations are catalog hints, not compatibility proof. Damage lives on the Character page; supports do not modify it yet."),
        ["WeaponSet"]=("Набор оружия","Weapon set"),
        ["WeaponSet1"]=("Набор I","Set I"), ["WeaponSet2"]=("Набор II","Set II"),
        ["WeaponSetBoth"]=("общий (оба набора)","both sets"),
        ["WeaponSetActive"]=("активен","active"),
        ["WeaponSetLegend"]=("красный — набор I, зелёный — набор II; считается только активный","red is set I, green set II; only the active set counts"),
        ["WeaponSetAssign"]=("Набор оружия этой ноды:","This node's weapon set:"),
        ["WeaponSetNodeActive"]=("Набор оружия: {0} — активен, модификаторы считаются","Weapon set: {0} — active, its modifiers count"),
        ["WeaponSetNodeInactive"]=("Набор оружия: {0} — неактивен, модификаторы не считаются","Weapon set: {0} — inactive, its modifiers do not count"),
        ["EquipmentSlots"]=("Слоты","Slots"), ["EquipmentInventory"]=("Хранилище предметов","Item storage"),
        ["NewItem"]=("Новый предмет","New item"), ["EditItem"]=("Изменить","Edit"),
        ["EquipItem"]=("Надеть","Equip"), ["UnequipItem"]=("Снять","Unequip"),
        ["DeleteItem"]=("Удалить","Delete"), ["DuplicateItem"]=("Дублировать","Duplicate"),
        ["ResetEquipment"]=("Очистить снаряжение…","Clear equipment…"),
        ["SearchItems"]=("Поиск предметов…","Search items…"),
        ["EmptySlot"]=("пусто","empty"), ["ItemLevelShort"]=("ур.","ilvl"),
        ["DeleteItemQuestion"]=("Удалить предмет? Он будет снят со слотов.","Delete this item? It will be removed from its slots."),
        ["ResetEquipmentQuestion"]=("Очистить всё снаряжение и хранилище? Действие можно отменить.","Clear all equipped and stored items? This can be undone."),
        ["SlotHelmet"]=("Шлем","Helmet"), ["SlotBody"]=("Доспех","Body Armour"),
        ["SlotGloves"]=("Перчатки","Gloves"), ["SlotBoots"]=("Обувь","Boots"),
        ["SlotBelt"]=("Пояс","Belt"), ["SlotAmulet"]=("Амулет","Amulet"),
        ["SlotRing1"]=("Кольцо 1","Ring 1"), ["SlotRing2"]=("Кольцо 2","Ring 2"),
        ["SlotMain1"]=("Осн. рука I","Main hand I"), ["SlotOff1"]=("Втор. рука I","Off hand I"),
        ["SlotMain2"]=("Осн. рука II","Main hand II"), ["SlotOff2"]=("Втор. рука II","Off hand II"),
        ["SlotLifeFlask"]=("Флакон HP","Life flask"), ["SlotManaFlask"]=("Флакон MP","Mana flask"),
        ["SlotCharm1"]=("Оберег 1","Charm 1"), ["SlotCharm2"]=("Оберег 2","Charm 2"), ["SlotCharm3"]=("Оберег 3","Charm 3"),
        ["ItemEditor"]=("Редактор предмета","Item editor"),
        ["BaseSearch"]=("Поиск базы…","Search bases…"),
        ["ModSearch"]=("Поиск модификаторов…","Search mods…"),
        ["AugmentSearch"]=("Поиск рун, ядер, идолов…","Search runes, cores, idols…"),
        ["ItemBase"]=("База","Base"), ["ItemName"]=("Название","Name"),
        ["ItemRarity"]=("Редкость","Rarity"), ["ItemLevel"]=("Уровень предмета","Item level"),
        ["ItemQuality"]=("Качество, %","Quality, %"), ["ItemSockets"]=("Гнёзда (указать вручную)","Sockets (set manually)"),
        ["ItemNotes"]=("Заметка","Note"),
        ["RarityNormal"]=("Обычный","Normal"), ["RarityMagic"]=("Волшебный","Magic"), ["RarityRare"]=("Редкий","Rare"),
        ["AvailableMods"]=("Доступные модификаторы","Available mods"),
        ["CurrentMods"]=("Модификаторы предмета","Item mods"),
        ["AddMod"]=("Добавить","Add"),
        ["ModValuesHint"]=("Значения — через «;», в пределах показанного диапазона.","Values separated by “;”, within the shown range."),
        ["AvailableAugments"]=("Доступные вставки","Available socketables"),
        ["CurrentAugments"]=("Вставлено","Socketed"),
        ["AugmentLimit"]=("Лимит: {0}","Limit: {0}"),
        ["BaseChangeQuestion"]=("Смена базы очистит модификаторы и вставки. Продолжить?","Changing the base clears mods and socketables. Continue?"),
        ["SaveItem"]=("Сохранить предмет","Save item"), ["Cancel"]=("Отмена","Cancel"),
        ["UnsavedDraftQuestion"]=("Закрыть без сохранения изменений?","Close without saving changes?"),
        ["PlanInvalid"]=("Недопустимый план.","Invalid plan."),
        ["PlanItemNumbers"]=("Уровень предмета 1–100, качество 0–20, гнёзда 0–6 — целыми числами.","Item level 1–100, quality 0–20, sockets 0–6 as whole numbers."),
        ["PlanSockets"]=("Сначала укажи число гнёзд: вставок не может быть больше.","Set the socket count first: socketables cannot exceed it."),
        ["PlanUnknownBase"]=("База отсутствует в каталоге.","Base is missing from the catalog."),
        ["PlanItemLevel"]=("Уровень предмета ниже минимального для этой базы.","Item level is below this base’s minimum."),
        ["PlanModInvalid"]=("Модификатор недоступен для этой базы или уровня предмета.","Mod is unavailable for this base or item level."),
        ["PlanModGroup"]=("Два модификатора из одной группы.","Two mods from the same group."),
        ["PlanModValues"]=("Значения вне диапазона модификатора.","Values are outside the mod’s range."),
        ["PlanAffixCap"]=("Превышен лимит префиксов или суффиксов для редкости.","Prefix/suffix cap exceeded for this rarity."),
        ["PlanAugmentInvalid"]=("Вставка не подходит этой базе.","Socketable does not fit this base."),
        ["PlanAugmentLimit"]=("Вставки с общим семейным лимитом пока не поддерживаются.","Socketables with a shared family limit are not supported yet."),
        ["PlanDataset"]=("План использует другой набор данных.","Plan uses a different dataset."),
        ["PlanSlot"]=("Предмет не подходит этому слоту.","Item does not fit this slot."),
        ["PlanQuiver"]=("Колчан требует лук в основной руке.","Quiver requires a bow in the main hand."),
        ["PlanTwoHand"]=("Двуручное оружие занимает обе руки.","Two-handed weapon occupies both hands."),
        ["PlanGemKind"]=("Активное умение и поддержки перепутаны местами.","Active skill and supports are mixed up."),
        ["PlanGemLevel"]=("Уровень недоступен для этого камня.","Level is unavailable for this gem."),
        ["SkillEditor"]=("Редактор группы умений","Skill group editor"),
        ["EditGroup"]=("Изменить","Edit"),
        ["DeleteGroup"]=("Удалить","Delete"), ["DuplicateGroup"]=("Дублировать","Duplicate"),
        ["ResetSkills"]=("Очистить умения…","Clear skills…"),
        ["GroupName"]=("Название группы","Group name"), ["GroupEnabled"]=("Группа активна","Group enabled"),
        ["GroupWeaponSet"]=("Набор оружия","Weapon set"), ["SetBoth"]=("Оба","Both"),
        ["ActiveGem"]=("Активное умение / дух","Active / spirit skill"),
        ["QuickAddHeader"]=("Быстрое добавление умения","Quick skill add"),
        ["QuickAdd"]=("Добавить","Add"),
        ["QuickAddHint"]=("Группа появляется сразу и называется по самому умению. Поддержки вставляются кликом по гнёздам на карточке; подробная правка — «✎» на карточке умения.","The group appears at once, named after the skill itself. Supports go into the sockets on the card; full editing via the pencil on the card."),
        ["QuickAdded"]=("Добавлено: {0}","Added: {0}"),
        ["CharacterSheet"]=("лист персонажа","character sheet"),
        ["SkillResultHeader"]=("Умения — итог","Skills — result"),
        ["SkillResultReadonly"]=("Итоговые цифры; правка умений — на страницах «Умения», «Снаряжение» и «Дерево».","Final numbers; edit skills on the Skills, Items or Tree pages."),
        ["SkillRateLabel"]=("Ударов/с","Hits/s"),
        ["SkillLevelLabel"]=("Уровень","Level"),
        ["SupportsInSkill"]=("Поддержки:","Supports:"),
        ["DamagePhys"]=("Физ. урон","Physical dmg"),
        ["DamageFire"]=("Урон огнём","Fire dmg"),
        ["DamageCold"]=("Урон холодом","Cold dmg"),
        ["DamageLight"]=("Урон молнией","Lightning dmg"),
        ["DamageChaos"]=("Урон хаосом","Chaos dmg"),
        ["BuildEdit"]=("Правка билда","Edit build"),
        ["BuildAscendancy"]=("Восхождение","Ascendancy"),
        ["BuildLevel"]=("Уровень","Level"),
        ["ProgressStageLabel"]=("Этап игры","Progress stage"),
        ["BuildStageStarter"]=("Стартер","Starter"),
        ["BuildStageEndgame"]=("Эндгейм","Endgame"),
        ["GameVersionLabel"]=("Версия игры","Game version"),
        ["ProgressStageHint"]=("«Стартер» — сопротивления считаются как есть; «эндгейм» — из каждого сопротивления вычитается 40 (штраф кампаний после Акта 3, до конца игры).","Starter counts resistances as-is; endgame subtracts 40 from each resistance (campaign penalty after Act 3)."),
        ["DialogueOk"]=("Готово","Done"),
        ["DialogueCancel"]=("Отмена","Cancel"),
        ["ImportCodeTitle"]=("Импорт билда","Import build"),
        ["ImportFileTitle"]=("Открыть .build / JSON","Open .build / JSON"),
        ["ImportIntro"]=("Код Path of Building декодируется локально. JSON — официальный формат Build Planner версии 1 (файл .build, экспорт poe.ninja). Ссылку можно вставить в любую вкладку: pobb.in открывается как код обмена, страница персонажа poe.ninja — через её собственный API. Загрузка выполняется один раз, только по нажатию «Импортировать».","PoB codes decode locally. JSON is the official Build Planner v1 format (.build file, poe.ninja export). A link works in either tab: pobb.in is read as a share code, a poe.ninja character page through its own API. A link is fetched once, only when you press Import."),
        ["ImportTabPob"]=("Код PoB","PoB code"),
        ["ImportTabJson"]=("JSON / ссылка","JSON / link"),
        ["ImportPobHint"]=("Строка-код обмена из Path of Building (base64url) либо ссылка pobb.in (https://pobb.in/…).","The share string from Path of Building (base64url), or a pobb.in link (https://pobb.in/…)."),
        ["ImportUrlLabel"]=("Ссылка на билд: pobb.in, страница персонажа poe.ninja, экспорт JSON","Build link: pobb.in, a poe.ninja character page, a JSON export"),
        ["ImportJsonLabel"]=("Текст JSON (экспорт poe.ninja или содержимое файла .build)","JSON text (poe.ninja export or a .build file's contents)"),
        ["ImportGo"]=("Импортировать","Import"),
        ["ImportPobBad"]=("Код не декодируется.","The code does not decode."),
        ["ImportUrlBad"]=("Ссылка должна начинаться с http:// или https://","The link must start with http:// or https://"),
        ["ImportFetchFailed"]=("Скачивание не удалось:","Download failed:"),
        ["ImportLinkNoCode"]=("Страница {0} открылась, но кода билда в ней нет: содержимое собирается скриптом в браузере. Скопируйте код кнопкой PoB на странице билда или вставьте ссылку pobb.in.","The {0} page opened but carries no build code: its content is assembled by a script in the browser. Copy the code with the PoB button on the build page, or paste a pobb.in link."),
        ["ImportNeither"]=("Строка не распознана ни как JSON, ни как код PoB.","The text is neither JSON nor a PoB code."),
        ["ImportNothing"]=("Введите код, JSON или ссылку.","Enter a code, JSON or a link."),
        ["ExchangeFilter"]=("Билды (*.build;*.json)|*.build;*.json|Все файлы (*.*)|*.*","Builds (*.build;*.json)|*.build;*.json|All files (*.*)|*.*"),
        ["PlannerFilter"]=("Файл билд-планировщика (*.build)|*.build","Build Planner file (*.build)|*.build"),
        ["ImportDialogTitle"]=("Открыть файл билда","Open build file"),
        ["ExportBuild"]=("Экспорт .build","Export .build"),
        ["ExportDone"]=("Экспортировано: {0}","Exported: {0}"),
        ["ImportFailed"]=("Импорт не удался:","Import failed:"),
        ["ImportReport"]=("Импорт завершён.\nПассивы: найдено {0}, не найдено {1} (узлы восхождения: {2}).\nУмения: активных {3}, поддержек {4}, нераспознанных камней {5}.\nСнаряжение перенесено: {6} предметов (самоцветов {7}, уников {8}); нераспознанных строк модов: {9}.","Import finished.\nPassives: matched {0}, unknown {1} (ascendancy nodes: {2}).\nSkills: {3} active, {4} supports, {5} unrecognized gems.\nEquipment transferred: {6} items (jewels {7}, uniques {8}); unrecognized mod lines: {9}."),
        ["ImportUnknownList"]=("Нераспознанные идентификаторы ({0} из полного списка):","Unrecognized ids ({0} of the full list):"),
        ["ImportSource"]=("Источник: {0}","Source: {0}"),
        ["NewStarted"]=("Создан билд: {0}","Build created: {0}"),
        ["OpenedStatus"]=("Открыт билд: {0}","Build opened: {0}"),
        ["SupportGems"]=("Поддержки","Supports"),
        ["GemSearch"]=("Поиск умений…","Search skills…"),
        ["SupportSearch"]=("Поиск поддержек…","Search supports…"),
        ["GemLevel"]=("Ур.","Lvl"), ["GemQuality"]=("Кач.","Qual"),
        ["AddSupport"]=("Добавить","Add"),
        ["SupportsCount"]=("Поддержки: {0} / 5","Supports: {0} / 5"),
        ["RecommendedSupports"]=("Рекомендации каталога — подсказка, не проверка","Catalog recommendations — a hint, not validation"),
        ["DeleteGroupQuestion"]=("Удалить группу умений?","Delete this skill group?"),
        ["ResetSkillsQuestion"]=("Очистить все группы умений? Действие можно отменить.","Clear all skill groups? This can be undone."),
        ["NoGroups"]=("Групп пока нет — создай первую.","No groups yet — create the first one."),
        ["Character"]=("Персонаж","Character"),
        ["IconsNotice"]=("Иконки предметов и камней — арт из Path of Exile 2 (© GGG, из публичных зеркал; см. NOTICE.txt). Соответствие патчу не зафиксировано.","Item and gem icons use Path of Exile 2 artwork (© GGG, via public mirrors; see NOTICE.txt). Patch parity is not pinned."),
        ["QualityNote"]=("Влияние качества на числа пока не рассчитывается: подтверждённая формула не подключена.","Quality does not affect numbers yet: no verified formula is connected."),
        ["SocketsHint"]=("Пустое гнездо — выбор поддержки. Крестик на заполненном — убрать.","Click an empty socket to pick a support. The small × removes a socketed gem."),
        ["RemoveSupport"]=("Убрать поддержку","Remove support"),
        ["SupportPickerTitle"]=("Камень поддержки","Support gem"),
        ["SupportPickerHint"]=("Поддержки из этой группы уже исключены из списка. Совместимость не проверяется — правила игры шире каталога.","Supports already in this group are hidden. Compatibility is not validated — game rules are broader than the catalog."),
        ["PickSupport"]=("Выбрать","Pick"),
        ["DpsPerSecond"]=("Урон/с:","DPS:"),
    ["EffectiveDps"]=("Эффективный (резисты врага):","effective (enemy res):"),
    ["DpsRaw"]=("без врага:","raw:"),
        ["CharacterSheet"]=("— экран персонажа (расчёты v1)","— character sheet (v1 calculations)"),
        ["LevelUp"]=("Уровень +1","Level +1"), ["LevelDown"]=("Уровень −1","Level −1"),
        ["Resources"]=("РЕСУРСЫ","RESOURCES"),
        ["CharLife"]=("Жизнь","Life"), ["CharMana"]=("Мана","Mana"), ["CharEnergyShield"]=("Энергетический щит","Energy Shield"),
        ["CharSpirit"]=("Дух","Spirit"), ["CharWard"]=("Ward","Ward"), ["CharLifeUnreserved"]=("Свободная жизнь","Unreserved life"), ["CharManaUnreserved"]=("Свободная мана","Unreserved mana"), ["CharSpiritUnreserved"]=("Свободный дух","Unreserved spirit"),
        ["TreeJewelGranted"]=("Предоставлено уникальным самоцветом","Granted by unique jewel"),
        ["Defences"]=("ЗАЩИТА","DEFENCE"),
        ["CharArmour"]=("Броня","Armour"), ["CharEvasion"]=("Уклонение","Evasion"), ["CharAccuracy"]=("Точность","Accuracy"),
        ["CharHitChance"]=("Шанс попадания","Hit chance"), ["CharMonsterHitChance"]=("Шанс попадания монстра","Monster hit chance"),
        ["CharBlock"]=("Шанс блока атаки","Attack block chance"), ["CharSpellBlock"]=("Шанс блока заклинаний","Spell block chance"), ["CharDodge"]=("Шанс уклонения атаки","Attack dodge chance"), ["CharSpellDodge"]=("Шанс уклонения заклинаний","Spell dodge chance"), ["CharSuppression"]=("Подавление заклинаний","Spell suppression"), ["CharDeflection"]=("Шанс отклонения","Deflection chance"),
        ["CharMoveSpeed"]=("Скорость передвижения","Movement speed"), ["CharLifeRegen"]=("Восстановление жизни","Life regen"),
        ["CharManaRegen"]=("Восстановление маны","Mana regen"), ["ManaRegenNote"]=("собственная регенерация 4% от максимальной маны в секунду + увеличение","inherent 4% of maximum Mana per second + increases"),
        ["NodeImpactNone"]=("(нода уже выделена или недоступна)","(node already allocated or unreachable)"), ["NodeImpactDefault"]=("При выделении добавит:","Allocating adds:"),
        ["ImpactDps"]=("УВС","DPS"), ["ImpactRate"]=("скорость","rate"), ["ImpactCrit"]=("крит","crit"),
        ["ImpactLife"]=("Жизнь","Life"), ["ImpactMana"]=("Мана","Mana"), ["ImpactEs"]=("ЭЩ","ES"),
        ["ImpactWard"]=("Оберег","Ward"), ["ImpactSpirit"]=("Дух","Spirit"), ["ImpactArmour"]=("Броня","Armour"),
        ["ImpactEvasion"]=("Уклонение","Evasion"), ["ImpactAccuracy"]=("Меткость","Accuracy"),
        ["ImpactFire"]=("Огонь","Fire"), ["ImpactCold"]=("Холод","Cold"), ["ImpactLightning"]=("Молния","Lightning"),
        ["ImpactChaos"]=("Хаос","Chaos"),
        ["ImpactAllocated"]=("При снятии уберёт:","Removing takes away:"),
        ["EhpPhysical"]=("EHP: физический удар","EHP: physical hit"), ["EhpExpectedAttack"]=("EHP: средняя атака монстра","EHP: expected monster attack"), ["EhpExpectedSpell"]=("EHP: явный spell scenario","EHP: explicit spell scenario"), ["EhpFire"]=("EHP: огонь","EHP: fire"),
        ["EhpCold"]=("EHP: холод","EHP: cold"), ["EhpLightning"]=("EHP: молния","EHP: lightning"), ["EhpChaos"]=("EHP: хаос","EHP: chaos"),
        ["EhpNote"]=("оценка против стандартного монстра {0} ур., размер удара {1}; успешный удар, эффективный raw pool {2}. Для хаоса ЭЩ получает двойной урон. Без учёта шанса попадания, блока, отклонения и восстановления.","estimate vs level-{0} default monster, hit size {1}; successful hit, effective raw pool {2}. Chaos deals double damage to ES. Hit chance, block, deflection and recovery excluded."),
        ["ExpectedEhpNote"]=("средняя атака: hit chance {0}%, block {1}%, deflection {2}%, dodge {3}%; blocked hit считается с 0% damage, deflected hit предотвращает 40%. Это physical-only estimate.","expected attack: hit chance {0}%, block {1}%, deflection {2}%, dodge {3}%; blocked hit uses 0% damage, deflected hit prevents 40%. Physical-only estimate."),
        ["ExpectedSpellEhpNote"]=("{0} scenario: hit chance {1}%, spell block {2}%, suppression {3}%, spell dodge {4}%. Raw hit и тип задаются explicit defence plan; mitigation остаётся bounded estimate.","{0} scenario: hit chance {1}%, spell block {2}%, suppression {3}%, spell dodge {4}%. Raw hit and type come from the explicit defence plan; mitigation remains a bounded estimate."),
        ["Attributes"]=("ХАРАКТЕРИСТИКИ","ATTRIBUTES"),
        ["AttrStrength"]=("Сила","Strength"), ["AttrDexterity"]=("Ловкость","Dexterity"), ["AttrIntelligence"]=("Интеллект","Intelligence"),
        ["Resistances"]=("СОПРОТИВЛЕНИЯ","RESISTANCES"),
        ["ResFire"]=("Огонь","Fire"), ["ResCold"]=("Холод","Cold"), ["ResLightning"]=("Молния","Lightning"), ["ResChaos"]=("Хаос","Chaos"),
        ["ResMax"]=("кап {0}%","cap {0}%"),
        ["ResTotal"]=("всего {0}%","total {0}%"),
        ["PerLevelShort"]=("за уровень","per level"), ["PerPoint"]=("за 1 пункт","per point"), ["PerSecondShort"]=("в секунду","per second"),
        ["PerStrengthShort"]=("за силу","per Str"), ["PerDexterityShort"]=("за ловкость","per Dex"), ["PerIntelligenceShort"]=("за интеллект","per Int"),
        ["EsRecharge"]=("восстановление {0} в секунду; старт через {1} с без урона по Щиту (без модели прерывания)","recharge {0}/s; starts after {1}s without ES damage (no interruption state)"),
        ["ReservationNote"]=("зарезервировано {0} из {1} ({2}%). Использован explicit resolved context.","reserved {0} of {1} ({2}%). Explicit resolved context supplied."),
        ["ArmourEstimate"]=("≈ −{0}% урона от удара монстра {1} ур. (A/(A+12·урон))","≈ −{0}% from a level-{1} monster hit (A/(A+12·dmg))"),
        ["EvasionNote"]=("рейтинг; шансы показаны против стандартного монстра уровня персонажа","rating; chances are shown against a same-level default monster"),
        ["HitChanceNote"]=("против стандартного монстра {0} ур.","against a level-{0} default monster"),
        ["MonsterHitChanceNote"]=("стандартный монстр {0} ур. против вашего уклонения","level-{0} default monster against your evasion"),
        ["BlockNote"]=("атака; максимум {0}% по текущему PoB2 reference","attack; maximum {0}% from the current PoB2 reference"),
        ["DodgeNote"]=("атака; cap 75% по текущему PoB2 reference; source stat из pinned SkillStatMap","attack; 75% cap from the current PoB2 reference; source stat from the pinned SkillStatMap"),
        ["SpellDodgeNote"]=("заклинания; cap 75% по текущему PoB2 reference; source stat из pinned SkillStatMap","spells; 75% cap from the current PoB2 reference; source stat from the pinned SkillStatMap"),
        ["SpellBlockNote"]=("заклинания; максимум {0}%; последствия блока пока не входят в EHP","spells; maximum {0}%; block consequences are not included in EHP yet"),
        ["SuppressionNote"]=("{0}% шанс; подавляется {1}% spell damage; пока не включено в EHP","{0}% chance; prevents {1}% of spell damage; not included in EHP yet"),
        ["DeflectionNote"]=("рейтинг {0}; отклонённый удар предотвращает {1}% урона; шанс — против точности стандартного монстра","rating {0}; a deflected hit prevents {1}% damage; chance is against the default monster accuracy"),
        ["SkillDamage"]=("УРОН УМЕНИЙ","SKILL DAMAGE"),
        ["KindAttack"]=("атака","attack"), ["KindSpell"]=("заклинание","spell"), ["KindSpirit"]=("дух","spirit"), ["KindOther"]=("умение","skill"),
        ["DpsCrit"]=("крит:","crit:"),
        ["DpsAvgHit"]=("средний удар:","avg hit:"), ["DpsMana"]=("мана:","mana:"),
        ["DpsUnit"]=("расчётный урон в секунду","estimated damage per second"),
        ["NoSkillsYet"]=("Групп умений пока нет. Создай их на странице «Умения».","No skill groups yet. Create them on the Skills page."),
        ["UnaccountedHeader"]=("НЕ УЧТЕНО: {0} статов","UNACCOUNTED: {0} stats"),
        ["UnaccountedNote"]=("Условные и особые эффекты не входят в расчёт v1. Полный список: Data/Game/unresolved-tree-lines.txt.","Conditional and special effects are outside v1. Full list: Data/Game/unresolved-tree-lines.txt."),
        ["Assumptions"]=("ДОПУЩЕНИЯ И ИСТОЧНИКИ","ASSUMPTIONS AND SOURCES"),
        ["AssumptionLevel"]=("Уровень: +12 жизни, +4 маны, +6 точности за уровень (PoB2 characterConstants).","Level: +12 life, +4 mana, +6 accuracy per level (PoB2 characterConstants)."),
        ["AssumptionAttributes"]=("Сила +2 жизни, Ловкость +6 точности, Интеллект +2 маны (PoB2 AccuracyPerDexBase=6).","Strength +2 life, Dexterity +6 accuracy, Intelligence +2 mana (PoB2 AccuracyPerDexBase=6)."),
        ["AssumptionCrit"]=("Базовый бонус крит. урона 100% (крит = 2×). Крит атак — от оружия, заклинаний — от камня.","Base Critical Damage Bonus 100% (crit = 2x). Attack crit from the weapon, spell crit from the gem."),
        ["AssumptionArmour"]=("Броня: −урон = A/(A+10·удар), не более 90% (PoB2 ArmourRatio=10); оценка против монстра уровня персонажа (данные RePoE default_monster_stats).","Armour: DR = A/(A+10·hit), capped 90% (PoB2 ArmourRatio=10); estimated against a same-level default monster (RePoE default_monster_stats)."),
        ["AssumptionBlock"]=("Блок атаки: базовый максимум 50%, дополнительные максимумы и override, общий cap 90%; spell block и последствия блокированного удара не считаются.","Attack block: 50% base maximum, maximum additions and override, 90% global cap; spell block and blocked-hit consequences are not calculated."),
        ["AssumptionSuppression"]=("Подавление заклинаний: chance cap 100%, базовый effect 50%; отображается только при наличии source stat и пока не входит в EHP.","Spell suppression: 100% chance cap, 50% base effect; shown only when a source stat exists and not included in EHP yet."),
        ["AssumptionDodge"]=("Dodge: attack/spell source stats проходят через cap 75%; строки появляются только при наличии source stat. Без source не выдумывается EHP contribution.","Dodge: attack/spell source stats use a 75% cap; rows appear only when a source stat exists. No EHP contribution is invented without a source."),
        ["AssumptionDeflection"]=("Отклонение: шанс по формуле PoB2 против точности стандартного монстра, cap 95%; отклонённый hit предотвращает базовые 40% урона. Entropy и сценарии не считаются.","Deflection: PoB2 chance formula against default-monster accuracy, capped at 95%; a deflected hit prevents the baseline 40% damage. Entropy and scenarios are not modeled."),
        ["AssumptionLifeRecovery"]=("Восстановление жизни: базовый regeneration per minute и распознанный increased life regeneration rate переводятся в panel rate. Окно восстановления — bounded estimate; leech, recoup, recovery locks и combat sequence не моделируются.","Life recovery: base regeneration per minute and mapped increased life regeneration rate are converted to a panel rate. Recovery windows are bounded estimates; leech, recoup, recovery locks and combat sequence are not modeled."),
        ["AssumptionEsRecharge"]=("Восстановление Щита: базовые 12,5%/с и старт через 4 с; модификаторы скорости учитываются. Окно и явная последовательность damage events доступны как bounded helpers; остальные состояния боя и active reservation context пока не моделируются.","ES recharge: base 12.5%/s and 4s start delay; speed modifiers are applied. A bounded window and explicit damage-event sequence helpers exist; other combat state and active reservation context are not modeled yet."),
        ["AssumptionHitChance"]=("Шанс попадания — формулы PoB2 rating-vs-rating с округлением и капом 5–100%; это оценка против стандартного монстра того же уровня. Поведение границ и патчевые детали требуют fixture/runtime проверки.","Hit chance uses PoB2 rating-vs-rating formulas with rounding and a 5–100% cap; this is a same-level default-monster estimate. Boundary and patch-specific behavior still require fixture/runtime verification."),
        ["AssumptionEhp"]=("EHP — вектор по типам урона для одного успешного удара стандартного монстра того же уровня: physical/elemental используют Жизнь + ЭЩ, хаос — Жизнь + половину ЭЩ из-за двойного урона по ЭЩ. Явный spell scenario может быть задан через DefenceScenarioPlan; hit chance, block, отклонение, подавление, восстановление, пробитие/экспозиция и bypass остаются ограниченными contract stages.","EHP is a damage-type vector for one successful same-level default-monster hit: physical/elemental use Life + ES, chaos uses Life + half ES because chaos deals double damage to ES. An explicit spell scenario can be supplied through DefenceScenarioPlan; hit chance, block, deflection, suppression, recovery, penetration/exposure and bypass remain limited contract stages."),
        ["AssumptionRes"]=("Сопротивления — эффективный результат = базовая линия этапа + сырые источники дерева/снаряжения/самоцветов, с верхним капом; рядом со строкой показаны перекап и полная сумма, а в детали — вклад источников. Ауры и постоянные навыки (Purity of Fire, а также предметные «Grants Skill: …» активного набора) считаются как в PoB2: значение = значение на уровне камня + целая часть качества×коэффициент, а повторы одного бафа сливаются по наибольшему значению.","Resistances show the effective result: stage baseline + raw tree/gear/jewel sources, with an upper cap; the overcapped part and the uncapped total sit beside each row, with the source sum in the detail. Auras and persistent skills (Purity of Fire and the item-granted \"Grants Skill: …\" lines of the active weapon set) follow PoB2: value = level value + the integral part of quality x coefficient, and repeated instances of one buff merge by their highest value."),
        ["AssumptionSupports"]=("Поддержки применяют закреплённые _final множители (скорость/крит/урон); неподдерживаемые помечаются подписями.","Supports apply pinned _final multipliers (rate/crit/damage); unsupported ones are noted."),
        ["AssumptionConversion"]=("Внутренние конверсии урона камней применяются (по статикам); «получить как» и source-gain-as учтены для атак и заклинаний.","In-skill damage conversion from gem statics is applied; 'gain as' and source-gain-as count for attacks and spells."),
        ["AssumptionQuality"]=("Качество предметов масштабирует базовые броню/уклонение/ЭС/Вард (+качества%) и местный физический урон оружия.","Item quality now scales base defences (+quality%) and the weapon's local physical damage."),
        ["AssumptionUniqueText"]=("Импортированные уники: распознанные строки текста (мана/жизнь/ЭС/Вард/рез/атрибуты/урон/скорость/крит) включены в расчёт — {0} шт.; нераспознанные моды и базовые защиты уников не в расчёте.","Imported uniques: recognised text modifiers (mana/life/ES/Ward/res/attributes/damage/speed/crit) are included ({0}); unrecognised lines and unique base defences stay out of the math."),
        ["CharacterCalcFailed"]=("Расчёт временно недоступен: ошибка вычисления (записана в журнал). Билд не изменён.","Calculations are temporarily unavailable: an evaluation error was journalled. The build is unchanged."),
        ["CharacterDataNotice"]=("Расчёты v1 по закреплённым данным (RePoE 4.5.5.2, дерево GGG 0.5.5, карты статов). Русские игровые тексты не подключены — имена предметов и камней EN.","v1 calculations over pinned data (RePoE 4.5.5.2, GGG 0.5.5 tree, stat maps). Russian game text is not connected — item and gem names remain EN."),
        ["ItemCorrupted"]=("Осквернён","Corrupted"),
        ["CorruptedHint"]=("Осквернение заменяет Implicit одним особым модом из пула базы (данные RePoE, вид corrupted). Обратимой операции нет.","Corruption replaces the implicit with one special mod from the base's pool (RePoE 'corrupted' data). Not reversible."),
        ["CorruptAdd"]=("Осквернить","Corrupt"),
        ["RemoveMod"]=("Убрать модификатор","Remove modifier"),
        ["RemoveAugment"]=("Убрать вставку","Remove socketable"),
        ["LevelFromItems"]=("+{0} ур. от предметов","+{0} levels from items"),
        ["ProgressStage"]=("Прогресс кампании","Campaign progress"),
        ["StageStarter"]=("Стартер","Starter"),
        ["StageEndgame"]=("Эндгейм","Endgame"),
        ["StageHint"]=("Стартер: сопротивления стартуют с 0%. Эндгейм: после кампании каждая стихия имеет −60% (штраф кампании, как в PoB2); хаос не штрафуется.","Starter: resistances start at 0%. Endgame: after the campaign each element sits at −60% (the campaign penalty, exactly like PoB2); Chaos is not penalised."),
        ["AssumptionResEndgame"]=("Сопротивления: кап 75% (до 90% максимумами); выбран «Эндгейм» — Огонь/Холод/Молния стартуют с −60% (штраф кампании, как в PoB2; хаос не штрафуется).","Resistances: 75% cap (up to 90% via maximums); Endgame selected — Fire/Cold/Lightning start at −60% (the campaign penalty, exactly like PoB2; Chaos not penalised)."),
        ["NoteDisabledGroup"]=("группа выключена","group disabled"),
        ["NoteSupportsExcluded"]=("поддержки не входят в расчёт","supports excluded from math"),
        ["NoteSupportsApplied"]=("поддержки учтены в расчёте","supports included in math"),
        ["NoteSupportsPartial"]=("часть поддержек без чисел в закреплённом источнике — не учтена","some supports lack pinned numbers — excluded"),
        ["NoteSupportFinalApprox"]=("множитель «только к максимуму урона» применён ко всему удару (приближение помечено)","maximum-only damage multiplier applied to the whole hit (labelled approximation)"),
        ["ResFromSources"]=("от дерева и снаряжения: {0}","from tree and gear: {0}"),
        ["RarityUnique"]=("Уникальный","Unique"),
        ["Jewels"]=("Самоцветы","Jewels"),
        ["JewelList"]=("Самоцветы в билде","Jewels in this build"),
        ["JewelCreate"]=("Создать самоцвет","Create jewel"),
        ["JewelEditor"]=("Редактор самоцвета","Jewel editor"),
        ["JewelFreeSockets"]=("Свободные гнёзда дерева (аллоцированные)","Free tree sockets (allocated)"),
        ["JewelFilledSockets"]=("Занятые гнёзда","Socketed"),
        ["JewelInsert"]=("Вставить в гнездо","Socket jewel"),
        ["JewelRemove"]=("Вынуть","Unsocket"),
        ["JewelSocketHint"]=("Гнездо появляется в списке, когда аллоцирован узел-гнездо на вкладке «Дерево» (1 очко).","A socket appears here once its jewel-socket node is allocated on the Tree tab (1 point)."),
        ["JewelSocketFailed"]=("Не удалось вставить: узел не является аллоцированным гнездом.","Could not socket: not an allocated jewel socket."),
        ["JewelUnnamed"]=("Безымянный самоцвет","Unnamed jewel"),
        ["JewelBasePick"]=("Самоцвет (базы и уникальные)", "Jewel (bases and uniques)"),
        ["JewelIconHint"]=("Картинка самоцвета: арт его базы из комплекта иконок; у уника — его собственный арт.", "The jewel's picture: its base's art from the icon pack, or a unique's own jewel art."),
        ["JewelUniqueVariant"]=("Вариант: {0}", "Variant: {0}"),
        ["JewelUniqueModifier"]=("Уникальный модификатор", "Unique modifier"),
        ["JewelBaseChangeNote"]=("Аффиксы другой базы (изумрудный суффикс на рубине) не выпадают, поэтому список аффиксов и уже добавленные строки чистятся при смене базы.", "Another base's affixes (an Emerald suffix on a Ruby) do not roll, so the affix list and the added lines are cleared when the base changes."),
        ["JewelUniquePick"]=("Уник-самоцвет (из каталога)","Unique jewel (from catalog)"),
        ["JewelUniquePickHint"]=("Поиск по закреплённому списку уникальных самоцветов","Search the pinned list of unique jewels"),
        ["JewelUniqueNotesHint"]=("Закреплённый каталог не содержит модификаторов уников — впиши их текст из игры в поле заметок вручную.","The pinned catalog has no unique modifiers — enter their text from the game manually in the notes field."),
        ["JewelBaseNote"]=("База самоцвета задаёт пул аффиксов и картинку; нейтральный «Diamond» принимает аффиксы всех трёх атрибутов. Самоцвет без базы (только импорт PoB) хранится как есть.", "A jewel's base decides its affix pool and its picture; Diamond accepts all three attributes' affixes. A baseless jewel (PoB imports only) is kept as it is."),
        ["JewelRadiusNote"]=("Аффиксы «в радиусе» (JewelRadius…) считаются по взятым узлам внутри круга самоцвета: полоса радиуса — из таблицы PoB2 (× 1,2), эффект применяется по одному разу на ноду. Незнакомые формулировки попадают в «не учтено».","Radius affixes (JewelRadius…) are counted per allocated node inside the jewel's circle: the band comes from PoB2's table (× 1.2) and each effect applies once per node. Wordings this model does not know stay reported."),
    ["TreeSocketEmpty"]=("Гнездо пустое. Самоцвет ставится на вкладке «Самоцветы».","This socket is empty. Jewels are socketed on the Jewels tab."),
    ["TreeSocketRadiusFlag"]=("(аффикс радиуса)","(radius affix)"),
    ["TreeSocketRadiusNote"]=("Круг радиуса нарисован по полосе самоцвета (таблица PoB2 × 1,2), и «… in Radius also grant …» считается по взятым узлам внутри него.","The radius circle is drawn from the jewel's band (PoB2's own table x 1.2), and \"… in Radius also grant …\" counts per allocated node inside it."),
        ["TreeSocketLabel"]=("Гнездо #{0}","Socket #{0}"),
        ["TreeRadiusDropped"]=("Самоцвет радиуса снят: {0} узл(ов), взятых вне связи через него, тоже сняты — как в игре.","The radius jewel is gone: {0} node(s) that were taken without a connection through it were refunded too, as the game does."),
        ["TreeRadiusRuleKeystone"]=("радиус «{0}»: узлы внутри можно брать без связи с деревом","radius of “{0}”: nodes inside can be allocated without a connection"),
        ["TreeRadiusRuleSocket"]=("радиус вокруг гнезда: узлы внутри можно брать без связи с деревом","radius around the socket: nodes inside can be allocated without a connection"),
        ["QualityNoteShort"]=("Качество указано, но на расчёт пока не влияет (формула не подключена).","Quality is recorded but does not affect the math yet (no verified formula)."),
        ["UniqueAllVariants"]=("Все версии","All versions"),
        ["UniqueNotesHint"]=("Уник: впиши модификаторы из игры — закреплённый каталог не содержит их текстов.","Unique: enter its modifiers from the game — the pinned catalog has no unique text."),
        ["UniqueLines"]=("Строки уники (данные PoB2)","Unique lines (PoB2 data)"),
        ["UniqueVariant"]=("Вариант","Variant"),
        ["UniqueVariantsHint"]=("Версия предмета, которую использует игра. Строки ниже — её модификаторы: значения можно править под свой предмет.", "The version of the item the game uses. The lines below are its modifiers — edit the values to match your item."),
        ["UniqueAllVariants"]=("Показать строки других вариантов","Show the lines of other variants"),
        ["UniqueVariantOnly"]=("вариант {0}","variant {0}"),
        ["UniqueTagged"]=("тег: {0}","tag: {0}"),
        ["UniqueVariantShown"]=("Вариант: {0}","Variant: {0}"),
        ["UniquePersonalMods"]=("Личные моды уники","The unique's own mods"),
        ["UniquePersonalModsHint"]=("Все модификаторы, которые эта уника может иметь: PoB2 хранит их по версиям предмета (Morior Invictus — «Spirit», «Life», «All Resistances» и т. д.), и в предмете по умолчанию стоит только его текущая версия. Выбери строку здесь и нажми «Добавить» — она станет модификатором предмета (и попадёт в расчёт), как «+10 to Spirit per Socket filled».","Every modifier this unique can have: PoB2 keeps one set per version of the item (Morior Invictus rolls \"Spirit\", \"Life\", \"All Resistances\"…), and only the live version's lines sit on the item by default. Pick a line here and press Add — it becomes one of the item's modifiers (and feeds the math), such as \"+10 to Spirit per Socket filled\"."),
        ["UniqueAddLine"]=("Добавить","Add"),
        ["RemoveLine"]=("Убрать строку","Remove line"),
        ["UniqueRoll"]=("Ролл","Roll"),
        ["UniqueRollHint"]=("Числовое значение этой строки: введи свой ролл в диапазоне {0}–{1}, и текст предмета обновится.","This line's numeric value: type your roll within {0}–{1} and the item text updates."),
        ["UniqueImplicitBadge"]=("IMPLICIT","IMPLICIT"),
        ["UniqueExplicitBadge"]=("МОДИФИКАТОР","MOD"),

        ["JewelNoBase"]=("самоцвет · базы нет в закреплённом каталоге","jewel · base missing from the pinned catalog"),
        ["GemMetaActive"]=("Активное умение · Уровень {0} · Качество: {1}%","Active skill · Level {0} · Quality: {1}%"),
        ["GemMetaSupport"]=("Камень поддержки · Уровень {0} · Качество: {1}%","Support gem · Level {0} · Quality: {1}%"),
        ["NoteWrongWeaponSet"]=("не соответствует набору оружия","does not match the weapon set"),
        ["NoteNoGemData"]=("нет поуровневых данных умения","no per-level skill data"),
        ["NoteNoWeapon"]=("нужно оружие в активном наборе","requires a weapon in the active set"),
        ["ConfigNotModelled"]=("Вкладка повторяет конфигурацию PoB2 в той части, которую считает наша модель, и не предлагает переключателей, которые ничего не меняют. Пока не поддержаны: заряды ярости/выносливости/силы, Onslaught, Arcane Surge, Unholy Might, crushed/intimidated/unnerved, враги рядом, тотемы и недавно призванные тотемы, consumed infusion, shapeshifted, сила озноба, Ash и Frost, боссы и их навыки, дистанция до врага, число цепей. Они появятся вместе с механиками, которые их читают — тогда же появятся и сами переключатели.","The tab mirrors PoB2's config only where our model can price it, and never offers a switch that would do nothing. Not modelled yet: frenzy/endurance/power charges, Onslaught, Arcane Surge, Unholy Might, crushed/intimidated/unnerved, nearby enemies, totems and recently summoned totems, consumed infusion, shapeshifted, chill effect, Ash and Frost, bosses and their skills, distance to enemy, number of chains. Each of them arrives together with the mechanic that reads it — and its switch arrives with it."),

        ["ConfigGeneral"]=("ОБЩЕЕ","GENERAL"),
        ["ConfigEndgame"]=("Эндгейм: штраф сопротивлений −60%","Endgame: −60% resistance penalty"),
        ["ConfigPenaltyNote"]=("Как в PoB2 («resistancePenalty»): стартовые персонажи получают 0%, эндгейм — −60%.","PoB2's \u0022resistancePenalty\u0022: starter characters get 0%, endgame −60%."),
        ["ConfigCombat"]=("В БОЮ","WHEN IN COMBAT"),
        ["ConfigMoving"]=("Вы всё время двигаетесь","You are always moving"),
        ["ConfigCritRecently"]=("Вы недавно нанесли критический удар","You have crit recently"),
        ["ConfigHitRecently"]=("По вам недавно попали","You have been hit recently"),
        ["ConfigFlameWall"]=("Огненная стена добавляет урон снарядам","Flame Wall adds damage to projectiles"),
        ["ConfigArcInfused"]=("Arc: «Lightning Infused» активен","Arc: Lightning Infused is active"),
        ["ConfigEffective"]=("ДЛЯ EFFECTIVE DPS · состояние врага","FOR EFFECTIVE DPS · enemy state"),
        ["ConfigEnemyChilled"]=("Враг охлаждён","Is the enemy chilled?"),
        ["ConfigEnemyIgnited"]=("Враг подожжён","Is the enemy ignited?"),
        ["ConfigEnemyBleeding"]=("Враг кровоточит","Is the enemy bleeding?"),
        ["ConfigEnemyShocked"]=("Враг шокирован","Is the enemy shocked?"),
        ["ConfigEnemyFireExposure"]=("Враг под воздействием огня (Exposure)","Is the enemy exposed to fire?"),
        ["ConfigEnemyColdExposure"]=("Враг под воздействием холода (Exposure)","Is the enemy exposed to cold?"),
        ["ConfigEnemyLightningExposure"]=("Враг под воздействием молнии (Exposure)","Is the enemy exposed to lightning?"),
        ["ConfigEnemyStats"]=("ХАРАКТЕРИСТИКИ ВРАГА","ENEMY STATS"),
        ["ConfigEnemyDefaults"]=("Пустое поле — значение PoB2 по умолчанию: 50% элементальных сопротивлений, 0% хаоса, броня монстра по уровню.","A blank field means PoB2's own default: 50% elemental resistance, 0% chaos, the level's monster armour."),
        ["ConfigEnemyLevel"]=("Уровень врага","Enemy level"),
        ["ConfigEnemyFire"]=("Сопротивление огню, %","Enemy fire resistance, %"),
        ["ConfigEnemyCold"]=("Сопротивление холоду, %","Enemy cold resistance, %"),
        ["ConfigEnemyLightning"]=("Сопротивление молнии, %","Enemy lightning resistance, %"),
        ["ConfigEnemyChaos"]=("Сопротивление хаосу, %","Enemy chaos resistance, %"),
        ["ConfigEnemyArmour"]=("Броня врага","Enemy armour"),
        ["ConfigEnemyPhysReduction"]=("Снижение физического урона, %","Enemy physical damage reduction, %"),
        ["ConfigReset"]=("Вернуть значения билда","Reset to the build's values"),
        ["ConfigApplied"]=("Конфигурация применена к расчёту.","Configuration applied to the calculation."),

        ["QuestRewards"]=("Награды за задания","Quest rewards"),
        ["QuestAll"]=("Отметить всё","Tick all"),
        ["QuestNone"]=("Снять всё","Untick all"),
        ["QuestImported"]=("Как в импорте","As imported"),
        ["QuestScope"]=("Таблица — собственная таблица PoB2 (src/Data/QuestRewards.lua). Отмеченные строки применяются в расчёте: сопротивления, жизнь и мана, дух, атрибуты, броня/уклонение/энергощит, скорость движения, восстановление маны и другое. Строку, которую модель пока не считает, расчёт честно перечисляет в «Допущениях» вкладки «Персонаж», а не выбрасывает. Каждый квест берётся один раз: два разных квеста могут давать одну и ту же строку.","The table is PoB2's own (src/Data/QuestRewards.lua). Ticked lines are what the calculation applies: resistances, life and mana, spirit, attributes, armour/evasion/energy shield, movement speed, mana regeneration and more. A line our model cannot price yet is reported in the Character tab's assumptions instead of being dropped. Every quest counts once: two different quests may grant the same line."),
        ["QuestRewardSummary"]=("Отмечено наград: {0} из {1}","Rewards ticked: {0} of {1}"),
        ["QuestRewardApplied"]=("В расчёт пойдут наград: {0}","Rewards applied to the build: {0}"),

        ["NoteNoDamageStats"]=("в данных умения нет урона","no damage values in skill data"),

        // RegEx tab. The generator is language-neutral — it builds from the pinned templates — so only the
        // chrome is localized here.
        ["RegExIntro"]=("Собери поисковую строку для фильтра предметов Path of Exile 2: её вставляют в поиск у торговца, на карте или в инвентаре. Модификаторы берутся из закреплённого каталога игры, поэтому строка всегда описывает настоящий аффикс.","Build the search string Path of Exile 2's item filter understands — paste it into the search box on a trader, a map device or your stash. Every modifier comes from the pinned game catalog, so a string can never describe an affix that does not exist."),
        ["RegExPick"]=("Отметь модификаторы","Pick modifiers"),
        ["RegExClickHint"]=("Клик по строке — обязательный (И), Shift+клик — необязательный (?), правый клик — исключить (✕). Поля «от» и «до» задают диапазон первого числа в строке.","Click a row to make it required (И), Shift+click for optional (?), right-click to exclude it (✕). The from/to boxes bound the first number of the line."),
        ["RegExModLevel"]=("ур.","lvl"),
        ["RegExLogic"]=("Условие","Logic"),
        ["RegExLogicMixed"]=("Смешанный","Mixed"), ["RegExLogicAll"]=("Все (И)","All (AND)"), ["RegExLogicAny"]=("Любой (ИЛИ)","Any (OR)"),
        ["RegExLogicMixedHint"]=("Обязательные соединяются через «И», необязательные — через «ИЛИ».","Required modifiers are AND-ed, optional ones OR-ed."),
        ["RegExLogicAllHint"]=("Нужны все отмеченные модификаторы.","Every picked modifier must be present."),
        ["RegExLogicAnyHint"]=("Достаточно одного из отмеченных.","Any one of the picked modifiers is enough."),
        ["RegExRequired"]=("обязательный","required"), ["RegExOptional"]=("необязательный","optional"),
        ["RegExExcluded"]=("исключить","excluded"), ["RegExOff"]=("не выбран","not picked"),
        ["RegExResult"]=("Готовая строка","Result"),
        ["RegExCopy"]=("Копировать","Copy"), ["RegExClear"]=("Очистить","Clear"),
        ["RegExLength"]=("{0} из {1} символов","{0} of {1} characters"),
        ["RegExReady"]=("Строка готова — вставьте её в поиск игры.","Ready — paste it into the game's search box."),
        ["RegExNearLimit"]=("Почти упирается в лимит: строка скоро станет слишком длинной.","Close to the limit: the string will soon be too long."),
        ["RegExOverflow"]=("ПЕРЕПОЛНЕНИЕ: строка длиннее 250 символов, игра её не примет. Снимите пару модификаторов или сузьте диапазоны.","OVERFLOW: the string is longer than 250 characters and the game will refuse it. Remove a modifier or narrow the ranges."),
        ["RegExCopied"]=("Скопировано в буфер обмена","Copied to the clipboard"),
        ["RegExTruncated"]=("Показаны первые {0} модификаторов — уточните поиск.","Showing the first {0} modifiers — narrow the search."),
        ["RegExBadBound"]=("Не число — диапазон не применён","Not a number — the bound was ignored"),
        ["RegExCatalogMissing"]=("Каталог предметов не загружен: вкладке нечего предложить.","The item catalog did not load, so the tab has nothing to offer."),
        ["RegExCatArmor"]=("Броня","Armour"), ["RegExCatWeapons"]=("Оружие","Weapons"),
        ["RegExCatJewel"]=("Самоцветы","Jewels"), ["RegExCatRing"]=("Кольца","Rings"),
        ["RegExCatAmulet"]=("Амулеты","Amulets"), ["RegExCatBelt"]=("Пояса","Belts"),
        ["RegExCatFlask"]=("Фляги","Flasks"), ["RegExCatOther"]=("Прочее","Other"),

        // Filter tab. The keywords, sounds and icon names stay in the game's own spelling — they are what the
        // file carries — so only the chrome is localized here.
        ["Filter"]=("Фильтр","Filter"),
        ["FilterName"]=("Название фильтра","Filter name"),
        ["FilterShowBadge"]=("ПОКАЗАТЬ","SHOW"), ["FilterHideBadge"]=("СКРЫТЬ","HIDE"),
        ["FilterIntro"]=("Редактор фильтра лута для Path of Exile 2. Соберите правила, сохраните фильтр в библиотеку и выгрузите файл в папку игры — там клиент его подхватит.","A Path of Exile 2 loot-filter editor. Build the rules, save the filter to the library, then write the file into the game's own folder, where the client picks it up."),
        ["FilterLibrary"]=("Библиотека фильтров","Filter library"),
        ["FilterLibraryCount"]=("Фильтров в библиотеке: {0}","{0} filter(s) in the library"),
        ["FilterLibraryUnreadable"]=("Не удалось прочитать файлов: {0} — они не удалены, проверьте их вручную.","{0} file(s) could not be read; they were kept, check them by hand"),
        ["FilterLibraryFailed"]=("Библиотека фильтров недоступна","The filter library could not be read"),
        ["FilterNew"]=("Новый фильтр","New filter"),
        ["FilterNewName"]=("Мой фильтр","My filter"),
        ["FilterNewStatus"]=("Создан новый фильтр. Выберите шаблон или добавьте правило.","A new filter was created. Pick a preset or add a rule."),
        ["FilterOpen"]=("Открыть","Open"),
        ["FilterSave"]=("Сохранить","Save"),
        ["FilterDuplicate"]=("Копия","Duplicate"),
        ["FilterDelete"]=("Удалить","Delete"),
        ["FilterDeleteQuestion"]=("Удалить фильтр? Он переместится в корзину и его можно будет вернуть.","Delete this filter? It moves to the trash and can be recovered."),
        ["FilterCopySuffix"]=("(копия)","(copy)"),
        ["FilterSaved"]=("Сохранено: {0}","Saved: {0}"),
        ["FilterSaveFailed"]=("Не удалось сохранить фильтр","The filter could not be saved"),
        ["FilterOpened"]=("Открыт фильтр: {0}","Opened: {0}"),
        ["FilterLoadFailed"]=("Не удалось открыть фильтр","The filter could not be opened"),
        ["FilterDuplicated"]=("Создана копия: {0}","Duplicated: {0}"),
        ["FilterDeleted"]=("Фильтр удалён","Filter deleted"),
        ["FilterDeleteFailed"]=("Не удалось удалить фильтр","The filter could not be deleted"),
        ["FilterMissing"]=("Фильтр не найден в библиотеке","The filter is not in the library"),
        ["FilterCleared"]=("Правила удалены","The rules were cleared"),
        ["FilterCopied"]=("Файл скопирован в буфер обмена","The file was copied to the clipboard"),
        ["FilterInvalid"]=("Фильтр пока нельзя сохранить","The filter cannot be saved yet"),
        ["FilterPresetLoaded"]=("Загружен шаблон: {0}","Preset loaded: {0}"),
        ["FilterPresets"]=("Шаблоны","Presets"),
        ["FilterRules"]=("Правила","Rules"),
        ["FilterAddShow"]=("Добавить «Показать»","Add Show"),
        ["FilterAddHide"]=("Добавить «Скрыть»","Add Hide"),
        ["FilterBlockComment"]=("Комментарий","Comment"),
        ["FilterDisabled"]=("Отключено","Disabled"),
        ["FilterCondition"]=("Условие","Condition"),
        ["FilterAddCondition"]=("Добавить условие","Add condition"),
        ["FilterRemoveCondition"]=("Убрать","Remove"),
        ["FilterUseRange"]=("Диапазон","Range"),
        ["FilterFrom"]=("от","from"), ["FilterTo"]=("до","to"),
        ["FilterStyle"]=("Оформление","Style"),
        ["FilterFontColor"]=("Цвет текста","Font colour"),
        ["FilterBorderColor"]=("Цвет рамки","Border colour"),
        ["FilterFontSize"]=("Размер шрифта","Font size"),
        ["FilterBorderWidth"]=("Толщина рамки","Border width"),
        ["FilterSound"]=("Звук","Sound"),
        ["FilterNoSound"]=("Без звука","No sound"),
        ["FilterFlare"]=("Вспышка","Flare"),
        ["FilterMinimapIcon"]=("Значок на миникарте","Minimap icon"),
        ["FilterNoIcon"]=("Без значка","No icon"),
        ["FilterColorHint"]=("Четыре числа 0–255 (R G B A). Пусто — цвет игры.","Four numbers 0–255 (R G B A). Empty keeps the game's own colour."),
        ["FilterPreview"]=("Файл фильтра","Filter file"),
        ["FilterCopy"]=("Копировать","Copy"),
        ["FilterExport"]=("Выгрузить в игру","Export to game"),
        ["FilterExportNothing"]=("Сначала добавьте хотя бы одно правило","Add at least one rule first"),
        ["FilterExported"]=("Файл записан: {0}","File written: {0}"),
        ["FilterExportFailed"]=("Не удалось выгрузить файл","The file could not be written"),
        ["FilterImport"]=("Загрузить .filter","Import .filter"),
        ["FilterImportTitle"]=("Открыть файл фильтра","Open a filter file"),
        ["FilterImportFilter"]=("Фильтры Path of Exile 2 (*.filter)|*.filter|Все файлы (*.*)|*.*","Path of Exile 2 filters (*.filter)|*.filter|All files (*.*)|*.*"),
        ["FilterImported"]=("Загружено правил: {0}","Imported {0} rule(s)"),
        ["FilterImportedUnknown"]=("Загружено правил, но {0} строк редактор не распознал — при сохранении они будут потеряны","Imported, but {0} line(s) were not recognised and will be lost on save"),
        ["FilterImportFailed"]=("Не удалось прочитать файл фильтра","The filter file could not be read"),
        ["FilterUnsaved"]=("не сохранено","not saved"),
        ["FilterDropLevel"]=("Уровень предметов","Item drop level"),
        ["FilterMinimap"]=("Иконки на миникарте","Minimap icons"),
        ["FilterLibrarySummary"]=("показать / скрыть","show / hide"),
        ["FilterRulesHint"]=("Правила проверяются сверху вниз: предмет подходит первому подошедшему правилу. Поэтому порядок важен.","Rules are checked top down: an item takes the first rule it matches, so the order matters."),
        ["FilterMoveUp"]=("Выше","Up"), ["FilterMoveDown"]=("Ниже","Down")
    };
}
