using System.ComponentModel;

namespace PoeBuilder.App.Services;

/// <summary>Application UI only. This is NOT a translation of PoE's game data.</summary>
public sealed class Localization : INotifyPropertyChanged
{
    private string _language = "ru";
    public string Language => _language;
    public event PropertyChangedEventHandler? PropertyChanged;
    public string this[string key] => Strings.TryGetValue(key, out var pair) ? (_language == "ru" ? pair.Ru : pair.En) : key;
    public void SetLanguage(string language)
    {
        if (language is not ("ru" or "en")) throw new ArgumentException("Unsupported UI language.");
        _language = language;
        PropertyChanged?.Invoke(this, new("Item[]"));
        PropertyChanged?.Invoke(this, new(nameof(Language)));
    }
    public string Format(string key, params object[] args) => string.Format(this[key], args);

    private static readonly Dictionary<string, (string Ru, string En)> Strings = new()
    {
        ["MainTree"]=("Основное дерево","Main tree"),
        ["Ascendancy"]=("Восхождение","Ascendancy"),
        ["AscendancyTree"]=("Мини-дерево восхождения","Ascendancy tree"),
        ["NoAscendancy"]=("Без восхождения","No ascendancy"),
        ["AscChangeQuestion"]=("Сменить восхождение? Узлы прежнего восхождения будут сброшены. Основное дерево останется. Действие можно отменить.","Change ascendancy? Previous ascendancy nodes will be cleared. The main tree is preserved. This can be undone."),
        ["TreeInvalidAscendancy"]=("Восхождение не соответствует классу или набору данных. План сохранён, редактирование заблокировано.","Ascendancy does not match this class or dataset. The plan is preserved; editing is blocked."),
        ["TreeClass"]=("Класс дерева","Tree class"),
        ["TreeDefaultAttribute"]=("Новые узлы атрибутов","New attribute nodes"),
        ["TreeAttribute"]=("Атрибут этого узла","This node’s attribute"),
        ["TreeLimit"]=("Лимит вручную (0 — нет)","Manual limit (0 = none)"),
        ["Apply"]=("Применить","Apply"),
        ["Undo"]=("Отменить шаг · Ctrl+Z","Undo · Ctrl+Z"),
        ["Redo"]=("Повторить шаг · Ctrl+Y","Redo · Ctrl+Y"),
        ["TreeDataNotice"]=("Данные GGG 0.5.5; соответствие 0.5.5c не подтверждено. ВНИМАНИЕ: русские игровые тексты пока не подключены — имена и свойства остаются EN даже при русском интерфейсе. Это незавершённая часть локализации.","GGG 0.5.5 data; equivalence to 0.5.5c is unverified. Russian game text is not yet connected: names and stats remain English even with Russian UI. Game localization is incomplete."),
        ["TreePoints"]=("Потрачено очков: {0} · без ручного лимита","Points spent: {0} · no manual limit"),
        ["TreePointsLimited"]=("Потрачено очков: {0} / {1} · ручной лимит","Points spent: {0} / {1} · manual limit"),
        ["TreeSearch"]=("ПОИСК УЗЛОВ · EN","FIND NODES · EN"),
        ["TreeSearchHint"]=("Имя, текст свойства или числовой ID. Поиск на английском.","Name, stat text or numeric ID. Search in English."),
        ["TreeSearchCount"]=("Найдено: {0} · в списке: {1}","Matches: {0} · listed: {1}"),
        ["TreeFocusClass"]=("К старту класса","Class start"),
        ["TreeFit"]=("Всё дерево","Fit tree"),
        ["TreeSelectNode"]=("Выбери узел","Select a node"),
        ["TreeInspectHint"]=("Щелчок — свойства и маршрут. Двойной щелчок — выделить путь.","Click to inspect stats and a route. Double-click to allocate the path."),
        ["TreeAllocate"]=("Выделить путь","Allocate path"),
        ["TreeRefund"]=("Снять узел / ветку","Refund node / branch"),
        ["TreeScope"]=("Основное дерево и отдельные графы восхождений. Лимиты очков раздельные и ручные; для восхождения начальное значение — 8. Безусловные бесплатные узлы не расходуют очки. Выборы внутри узлов, условные выделения, дополнительные очки и наборы оружия ещё заблокированы. Эффекты узлов входят в экран «Персонаж» (безусловные статы).","Main tree and separate ascendancy graphs. Point limits are separate and manual; the initial ascendancy limit is 8. Unconditional free nodes cost no points. Multiple-choice nodes, conditional allocations, extra points and weapon sets remain blocked. Node effects feed the Character sheet (unconditional stats)."),
        ["TreeBrowseOnly"]=("Режим просмотра. Создай или открой билд, чтобы выбрать класс и сохранять дерево.","Browse mode. Create or open a build to choose a class and save a tree plan."),
        ["TreeResetPlan"]=("Очистить план дерева…","Clear tree plan…"),
        ["TreeResetQuestion"]=("Очистить план дерева? Основное дерево и восхождение будут сброшены. Метаданные и заметки останутся. Действие можно отменить.","Clear the tree plan? Main allocations and ascendancy will be reset. Metadata and notes remain. This can be undone."),
        ["TreeChangeClassQuestion"]=("Смена класса очистит основное дерево и восхождение. Продолжить? Действие можно отменить.","Changing class clears the main tree and ascendancy. Continue? This can be undone."),
        ["TreeRefundQuestion"]=("Будет снято узлов: {0}, включая ветки, которые потеряют связь со стартом. Продолжить?","Refund {0} nodes, including branches that would lose their connection to the start?"),
        ["TreeDatasetMismatch"]=("План использует другой набор данных. Изменение дерева заблокировано; исходный план сохранён. Можно явно очистить дерево.","This plan uses a different dataset. Editing is blocked; the original plan is preserved. You can explicitly clear the tree."),
        ["TreeInvalidClass"]=("Этот класс недоступен в подключённом наборе. План не изменён.","This class is unavailable in the loaded dataset. The plan has not been changed."),
        ["TreeInvalidSaved"]=("План содержит отсутствующие или неподдерживаемые узлы. Изменение заблокировано; данные сохранены.","This plan contains missing or unsupported nodes. Editing is blocked; data is preserved."),
        ["TreeOverBudget"]=("Недостаточно очков по заданному вручную лимиту.","This exceeds the manually configured point limit."),
        ["TreeInvalidAttribute"]=("Недопустимый выбор атрибута. План не изменён.","Invalid attribute selection. The plan has not been changed."),
        ["TreeDisconnected"]=("В плане есть узлы без связи со стартом класса. Изменение заблокировано.","The plan contains nodes disconnected from its class start. Editing is blocked."),
        ["TreeUnsupported"]=("Узел недоступен: специальная механика, условие, выбор варианта или чужой старт.","Unavailable node: special mechanic, condition, multiple-choice option or another class start."),
        ["TreeNoPath"]=("Нет доступного пути через поддерживаемые узлы.","No route exists through supported nodes."),
        ["TreeInvalidLimit"]=("Введите целое число от 0 до 10000. 0 — без ручного лимита.","Enter a whole number from 0 to 10000. 0 means no manual limit."),
        ["TreeStartInfo"]=("Старт выбранного класса. Не расходует очки и не снимается.","Selected class start. Costs no points and cannot be refunded."),
        ["TreeJewelInfo"]=("Гнездо выделено. Самоцвет можно установить на вкладке «Самоцветы»; эффекты радиуса и уникальные механики пока ограничены.","Socket allocated. Equip a jewel on the Jewels tab; radius effects and unique mechanics remain limited."),
        ["TreeAllocated"]=("Узел выделен.","Node allocated."),
        ["TreePathCost"]=("Кратчайший путь: +{0} очк.","Shortest path: +{0} points."),
        ["TreeLocked"]=("недоступно","unavailable"),
        ["TreeLoadFailed"]=("Не удалось загрузить проверенный набор дерева. Билды не изменены.","Could not load the verified tree dataset. Builds were not modified."),
        ["TreeAtlasFailed"]=("Не удалось загрузить иконки дерева. Узлы показаны без иконок.","Tree icons could not be loaded. Nodes are shown without icons."),
        ["Workspace"]=("РАБОЧЕЕ ПРОСТРАНСТВО","WORKSPACE"),
        ["Builds"]=("Мои билды","My builds"), ["Tree"]=("Дерево навыков","Passive tree"),
        ["Skills"]=("Умения","Skills"), ["Items"]=("Снаряжение","Equipment"),
        ["Configuration"]=("Конфигурация","Configuration"), ["Calculations"]=("Расчёты","Calculations"),
        ["Notes"]=("Заметки","Notes"), ["Settings"]=("Настройки","Settings"),
        ["Independent"]=("Независимый проект · C# / WPF","Independent project · C# / WPF"),
        ["Alpha"]=("РАСЧЁТЫ · АЛЬФА (v1)","CALCULATIONS · ALPHA (v1)"),
        ["Save"]=("Сохранить","Save"), ["Import"]=("Импорт","Import"), ["Export"]=("Экспорт","Export"),
        ["NewBuild"]=("Новый билд","New build"), ["CreateBuild"]=("Создать билд","Create build"),
        ["HeroBadge"]=("PATH OF EXILE 2  /  НЕОФИЦИАЛЬНЫЙ ПЛАНИРОВЩИК","PATH OF EXILE 2  /  UNOFFICIAL BUILD PLANNER"),
        ["HeroTitle"]=("Каждый билд\nначинается с идеи.","Every build\nbegins with an idea."),
        ["HeroDescription"]=("Своё пространство для персонажей, планов и экспериментов.","Your own space for characters, plans and experiments."),
        ["Library"]=("Библиотека билдов","Build library"),
        ["SearchHint"]=("Поиск по названию и классу…","Search by name or class…"),
        ["LibrarySubtitle"]=("Локальное хранение. Твои идеи остаются у тебя.","Stored locally. Your ideas stay with you."),
        ["EmptyLibrary"]=("Здесь появятся твои билды","Your builds will appear here"),
        ["EmptyLibraryText"]=("Создай первый билд или импортируй файл PoeBuilder Native.","Create your first build or import a PoeBuilder Native file."),
        ["NoResults"]=("По этому запросу ничего не найдено","No builds match this search"),
        ["OpenBuild"]=("Открыть","Open"), ["Duplicate"]=("Копия","Duplicate"), ["Delete"]=("Удалить","Delete"),
        ["Level"]=("Уровень","Level"), ["UnspecifiedClass"]=("Класс не указан","Class not specified"),
        ["CurrentBuild"]=("ТЕКУЩИЙ БИЛД","CURRENT BUILD"), ["NoBuild"]=("Билд не выбран","No build selected"),
        ["Saved"]=("Сохранено локально","Saved locally"), ["Unsaved"]=("Есть изменения","Unsaved changes"),
        ["Draft"]=("Новый черновик","New draft"),
        ["Name"]=("Название билда","Build name"), ["Class"]=("Класс / персонаж","Class / character"),
        ["ClassHint"]=("Свободная подпись. Игровой класс выбирается в дереве.","Free-text label. Select the game class on the tree page."),
        ["TargetVersion"]=("Целевая версия игры","Target game version"),
        ["VersionHint"]=("Метка проекта. Не подтверждает поддержку механик патча.","A project label. It does not imply support for that patch's mechanics."),
        ["Profile"]=("Параметры персонажа","Character profile"),
        ["ProfileSubtitle"]=("Метаданные билда уже сохраняются. Игровые модификаторы будут подключены отдельно.","Build metadata is persisted. Game modifiers will be connected separately."),
        ["NoBuildText"]=("Сначала создай или открой билд в библиотеке.","Create or open a build from the library first."),
        ["DataMissing"]=("Игровые данные ещё не подключены","Game data is not connected yet"),
        ["DataBadge"]=("НЕТ НАБОРА ДАННЫХ","NO DATASET"),
        ["TreeText"]=("Это рабочее поле будущего редактора, а не дерево PoE 2.\nУзлы появятся после подключения проверенных игровых данных.","This is the future editor's workspace, not the PoE 2 tree.\nNodes will appear after verified game data is connected."),
        ["TreeControls"]=("Колесо — масштаб · Перетаскивание — обзор · Щелчок — свойства · Двойной щелчок / Enter — выделить · Delete — снять · Ctrl+Z / Ctrl+Y — история (при фокусе на дереве)","Wheel: zoom · Drag: pan · Click: inspect · Double-click / Enter: allocate · Delete: refund · Ctrl+Z / Ctrl+Y: history (with tree focused)"),
        ["ResetView"]=("По центру","Reset view"),
        ["ZoomIn"]=("Увеличить","Zoom in"), ["ZoomOut"]=("Уменьшить","Zoom out"),
        ["SkillsTitle"]=("Собери свою связку умений","Plan your skill setup"),
        ["SkillsText"]=("Редактор групп активных умений и поддержек уже подключён. Уровни и качество импортируются; поддержками и совместимостью пока управляет ограниченный v1-калькулятор.","The active-skill and support-group editor is connected. Levels and quality are imported; support effects and compatibility remain limited in the v1 calculator."),
        ["ItemsTitle"]=("Снаряжение без компромиссов","Make every equipment choice count"),
        ["ItemsText"]=("Каталог баз, модификаторов, гнёзд и вставок подключён. Импорт PoB сохраняет поддерживаемые предметы, а неизвестные строки показывает в отчёте.","Base items, modifiers, sockets and socketables are connected. PoB import preserves supported items and reports unknown lines."),
        ["CalcsTitle"]=("Прозрачные расчёты","Transparent calculations"),
        ["CalcsText"]=("Экран персонажа показывает расчёты v1 по закреплённым данным и явно перечисляет допущения. Полный PoB combat pipeline, условия врага и часть механик пока не подключены.","The Character sheet shows v1 calculations over pinned data and lists its assumptions. The full PoB combat pipeline, enemy conditions and some mechanics are not connected yet."),
        ["Damage"]=("УРОН В СЕКУНДУ","DAMAGE PER SECOND"), ["Defence"]=("ВЫЖИВАЕМОСТЬ","SURVIVABILITY"),
        ["Resources"]=("РЕСУРСЫ","RESOURCES"), ["NotCalculated"]=("Не рассчитано","Not calculated"),
        ["NotesTitle"]=("Запиши следующий шаг","Keep your next idea close"),
        ["NotesSubtitle"]=("Планы развития, варианты экипировки и свои наблюдения.","Progression plans, equipment ideas and your own observations."),
        ["NotesHint"]=("Заметки хранятся в файле билда. Сохранение: Ctrl+S.","Notes are stored in the build file. Save with Ctrl+S."),
        ["Appearance"]=("Интерфейс","Interface"), ["Language"]=("Язык приложения","Application language"),
        ["LanguageText"]=("Применяется сразу, без перезапуска.","Applied immediately. No restart required."),
        ["LocaleNotice"]=("Этот переключатель переводит интерфейс PoeBuilder. Официальные русские названия и описания из игры ещё не подключены.","This switch localizes the PoeBuilder interface. Official Russian game names and descriptions are not connected yet."),
        ["Storage"]=("Локальные данные","Local data"), ["OpenFolder"]=("Открыть папку","Open folder"),
        ["StorageText"]=("Билды и настройки хранятся отдельно от старого проекта и оригинального PoB. Облачной синхронизации и отправки данных нет.","Builds and settings are separate from the old project and original PoB. No cloud sync or data transmission."),
        ["ProjectStatus"]=("Статус проекта","Project status"),
        ["ProjectStatusText"]=("Собственный C# / WPF проект без PoB, Lua и SimpleGraphic. Уже работают библиотека билдов, дерево, восхождения, снаряжение, умения, импорт PoB и расчёты v1. Полный PoB-паритет, русский игровой текст и условные combat mechanics ещё не заявляются.","Independent C# / WPF project without PoB, Lua or SimpleGraphic. Build library, tree, ascendancies, equipment, skills, PoB import and v1 calculations are connected. Full PoB parity, Russian game text and conditional combat mechanics are not claimed yet."),
        ["Ready"]=("Готово","Ready"), ["Loading"]=("Загрузка…","Loading…"),
        ["SavedStatus"]=("Билд сохранён: {0}","Build saved: {0}"),
        ["ImportedStatus"]=("Импортирована новая копия: {0}","Imported a new copy: {0}"),
        ["ExportedStatus"]=("Файл билда экспортирован","Build file exported"),
        ["DeletedStatus"]=("Билд перемещён в локальную корзину","Build moved to local trash"),
        ["SkippedFiles"]=("Не прочитано файлов: {0}. Они не изменены.","Unreadable files: {0}. They were left unchanged."),
        ["SettingsRecovered"]=("Настройки не прочитаны. Использованы стандартные значения.","Settings could not be read. Defaults were used."),
        ["Error"]=("Не удалось выполнить действие","The action could not be completed"),
        ["ErrorText"]=("Изменения в редакторе не сброшены. Технические подробности:","Your editor changes were not discarded. Technical details:"),
        ["Confirm"]=("PoeBuilder — подтверждение","PoeBuilder — confirmation"),
        ["UnsavedQuestion"]=("Сохранить изменения в текущем билде?\n\nДа — сохранить. Нет — отбросить. Отмена — остаться.","Save changes to the current build?\n\nYes: save. No: discard. Cancel: stay here."),
        ["DeleteQuestion"]=("Переместить «{0}» в локальную корзину?\nФайл останется в подпапке Builds\\Trash.","Move “{0}” to local trash?\nThe file will remain in Builds\\Trash."),
        ["NameError"]=("Укажи название от 1 до 80 символов и уровень от 1 до 100.","Enter a name of 1–80 characters and a level from 1 to 100."),
        ["CopyName"]=("{0} — копия","{0} — copy"), ["NewName"]=("Мой новый билд","My new build"),
        ["NativeFilter"]=("Билд PoeBuilder Native (*.poebuild)|*.poebuild","PoeBuilder Native build (*.poebuild)|*.poebuild"),
        ["ImportTitle"]=("Импорт файла PoeBuilder Native — не кода PoB","Import a PoeBuilder Native file — not a PoB code"),
        ["Close"]=("Закрыть","Close"), ["Minimize"]=("Свернуть","Minimize"), ["Maximize"]=("Развернуть / восстановить","Maximize / restore"),
        ["BuildCount"]=("Билдов: {0}","Builds: {0}"),
        ["FoundationNotice"]=("Работают библиотека, заметки, RU/EN интерфейс, дерево и восхождения GGG 0.5.5, снаряжение и умения (каталог RePoE 4.5.5.2 EN, иконки GGG), расчёты v1 на экране «Персонаж».","Library, notes, RU/EN UI, GGG 0.5.5 tree and ascendancies, equipment and skills (RePoE 4.5.5.2 EN catalog, GGG icons), v1 calculations on the Character page."),
    
        ["CatalogMissing"]=("Каталог предметов и умений не загружен. Проверь установку: нужен файл Data\\Game\\catalog.json.","The equipment/skill catalog failed to load. Check the install: Data\\Game\\catalog.json is required."),
        ["GameDataNotice"]=("Каталог: сторонний снимок RePoE PoE2 4.5.5.2 (EN). Соответствие патчу 0.5.5c не подтверждено; игровые тексты остаются английскими.","Catalog: third-party RePoE PoE2 snapshot 4.5.5.2 (EN). Equivalence to patch 0.5.5c is unverified; game text remains English."),
        ["EquipmentScope"]=("Слоты в духе инвентаря. Нажатие открывает редактор: база, модификаторы из пула базы, качество, гнёзда с рунами, ядрами и идолами. Уникальные предметы, крафт и импорт из игры — позже. Итоги — на странице «Персонаж» (урон, защита, сопротивления).","Inventory-style slots. Clicking a slot opens the editor: base, mods from that base’s pool, quality, sockets with runes, cores and idols. Uniques, crafting and game import come later. Totals live on the Character page (damage, defence, resistances)."),
        ["SkillsScope"]=("Группы: активное умение или дух + до 5 поддержек, уровень и качество. Рекомендации — подсказка каталога, не проверка совместимости. Урон считается на экране «Персонаж»; поддержки пока не усиливают его.","Groups: one active or spirit skill plus up to 5 supports, with level and quality. Recommendations are catalog hints, not compatibility proof. Damage lives on the Character page; supports do not modify it yet."),
        ["WeaponSet"]=("Набор оружия","Weapon set"),
        ["WeaponSet1"]=("Набор I","Set I"), ["WeaponSet2"]=("Набор II","Set II"),
        ["EquipmentSlots"]=("Слоты","Slots"), ["EquipmentInventory"]=("Хранилище предметов","Item storage"),
        ["NewItem"]=("Новый предмет","New item"), ["EditItem"]=("Изменить","Edit"),
        ["EquipItem"]=("Надеть","Equip"), ["UnequipItem"]=("Снять","Unequip"),
        ["DeleteItem"]=("Удалить","Delete"), ["DuplicateItem"]=("Дублировать","Duplicate"),
        ["ResetEquipment"]=("Очистить снаряжение…","Clear equipment…"),
        ["SearchItems"]=("Поиск предметов…","Search items…"),
        ["EmptySlot"]=("пусто","empty"), ["ItemLevelShort"]=("ур.","ilvl"),
        ["DeleteItemQuestion"]=("Удалить предмет? Он будет снят со слотов.","Delete this item? It will be removed from its slots."),
        ["ResetEquipmentQuestion"]=("Очистить всё снаряжение и хранилище? Действие можно отменить.","Clear all equipped and stored items? This can be undone."),
        ["SlotHelmet"]=("Шлем","Helmet"), ["SlotBody"]=("Доспех","Body Armour"),
        ["SlotGloves"]=("Перчатки","Gloves"), ["SlotBoots"]=("Обувь","Boots"),
        ["SlotBelt"]=("Пояс","Belt"), ["SlotAmulet"]=("Амулет","Amulet"),
        ["SlotRing1"]=("Кольцо 1","Ring 1"), ["SlotRing2"]=("Кольцо 2","Ring 2"),
        ["SlotMain1"]=("Осн. рука I","Main hand I"), ["SlotOff1"]=("Втор. рука I","Off hand I"),
        ["SlotMain2"]=("Осн. рука II","Main hand II"), ["SlotOff2"]=("Втор. рука II","Off hand II"),
        ["SlotLifeFlask"]=("Флакон HP","Life flask"), ["SlotManaFlask"]=("Флакон MP","Mana flask"),
        ["SlotCharm1"]=("Оберег 1","Charm 1"), ["SlotCharm2"]=("Оберег 2","Charm 2"), ["SlotCharm3"]=("Оберег 3","Charm 3"),
        ["ItemEditor"]=("Редактор предмета","Item editor"),
        ["BaseSearch"]=("Поиск базы…","Search bases…"),
        ["ModSearch"]=("Поиск модификаторов…","Search mods…"),
        ["AugmentSearch"]=("Поиск рун, ядер, идолов…","Search runes, cores, idols…"),
        ["ItemBase"]=("База","Base"), ["ItemName"]=("Название","Name"),
        ["ItemRarity"]=("Редкость","Rarity"), ["ItemLevel"]=("Уровень предмета","Item level"),
        ["ItemQuality"]=("Качество, %","Quality, %"), ["ItemSockets"]=("Гнёзда (указать вручную)","Sockets (set manually)"),
        ["ItemNotes"]=("Заметка","Note"),
        ["RarityNormal"]=("Обычный","Normal"), ["RarityMagic"]=("Волшебный","Magic"), ["RarityRare"]=("Редкий","Rare"),
        ["AvailableMods"]=("Доступные модификаторы","Available mods"),
        ["CurrentMods"]=("Модификаторы предмета","Item mods"),
        ["AddMod"]=("Добавить","Add"),
        ["ModValuesHint"]=("Значения — через «;», в пределах показанного диапазона.","Values separated by “;”, within the shown range."),
        ["AvailableAugments"]=("Доступные вставки","Available socketables"),
        ["CurrentAugments"]=("Вставлено","Socketed"),
        ["AugmentLimit"]=("Лимит: {0}","Limit: {0}"),
        ["BaseChangeQuestion"]=("Смена базы очистит модификаторы и вставки. Продолжить?","Changing the base clears mods and socketables. Continue?"),
        ["SaveItem"]=("Сохранить предмет","Save item"), ["Cancel"]=("Отмена","Cancel"),
        ["UnsavedDraftQuestion"]=("Закрыть без сохранения изменений?","Close without saving changes?"),
        ["PlanInvalid"]=("Недопустимый план.","Invalid plan."),
        ["PlanItemNumbers"]=("Уровень предмета 1–100, качество 0–20, гнёзда 0–6 — целыми числами.","Item level 1–100, quality 0–20, sockets 0–6 as whole numbers."),
        ["PlanSockets"]=("Сначала укажи число гнёзд: вставок не может быть больше.","Set the socket count first: socketables cannot exceed it."),
        ["PlanUnknownBase"]=("База отсутствует в каталоге.","Base is missing from the catalog."),
        ["PlanItemLevel"]=("Уровень предмета ниже минимального для этой базы.","Item level is below this base’s minimum."),
        ["PlanModInvalid"]=("Модификатор недоступен для этой базы или уровня предмета.","Mod is unavailable for this base or item level."),
        ["PlanModGroup"]=("Два модификатора из одной группы.","Two mods from the same group."),
        ["PlanModValues"]=("Значения вне диапазона модификатора.","Values are outside the mod’s range."),
        ["PlanAffixCap"]=("Превышен лимит префиксов или суффиксов для редкости.","Prefix/suffix cap exceeded for this rarity."),
        ["PlanAugmentInvalid"]=("Вставка не подходит этой базе.","Socketable does not fit this base."),
        ["PlanAugmentLimit"]=("Вставки с общим семейным лимитом пока не поддерживаются.","Socketables with a shared family limit are not supported yet."),
        ["PlanDataset"]=("План использует другой набор данных.","Plan uses a different dataset."),
        ["PlanSlot"]=("Предмет не подходит этому слоту.","Item does not fit this slot."),
        ["PlanQuiver"]=("Колчан требует лук в основной руке.","Quiver requires a bow in the main hand."),
        ["PlanTwoHand"]=("Двуручное оружие занимает обе руки.","Two-handed weapon occupies both hands."),
        ["PlanGemKind"]=("Активное умение и поддержки перепутаны местами.","Active skill and supports are mixed up."),
        ["PlanGemLevel"]=("Уровень недоступен для этого камня.","Level is unavailable for this gem."),
        ["SkillEditor"]=("Редактор группы умений","Skill group editor"),
        ["NewGroup"]=("Новая группа","New group"), ["EditGroup"]=("Изменить","Edit"),
        ["DeleteGroup"]=("Удалить","Delete"), ["DuplicateGroup"]=("Дублировать","Duplicate"),
        ["ResetSkills"]=("Очистить умения…","Clear skills…"),
        ["GroupName"]=("Название группы","Group name"), ["GroupEnabled"]=("Группа активна","Group enabled"),
        ["GroupWeaponSet"]=("Набор оружия","Weapon set"), ["SetBoth"]=("Оба","Both"),
        ["ActiveGem"]=("Активное умение / дух","Active / spirit skill"),
        ["QuickAddHeader"]=("Быстрое добавление умения","Quick skill add"),
        ["QuickAdd"]=("Добавить","Add"),
        ["QuickAddHint"]=("Группа называется по самому умению. Поддержки вставляются кликом по гнёздам на карточке; подробная правка — «Изменить» на карточке умения.","The group is named after the skill itself. Supports go into sockets on the card; full editing via Edit on the card."),
        ["QuickAdded"]=("Добавлено: {0}","Added: {0}"),
        ["CharacterSheet"]=("лист персонажа","character sheet"),
        ["SkillResultHeader"]=("Умения — итог","Skills — result"),
        ["SkillResultReadonly"]=("Итоговые цифры; правка умений — на страницах «Умения», «Снаряжение» и «Дерево».","Final numbers; edit skills on the Skills, Items or Tree pages."),
        ["SkillRateLabel"]=("Ударов/с","Hits/s"),
        ["SkillLevelLabel"]=("Уровень","Level"),
        ["SupportsInSkill"]=("Поддержки:","Supports:"),
        ["DamagePhys"]=("Физ. урон","Physical dmg"),
        ["DamageFire"]=("Урон огнём","Fire dmg"),
        ["DamageCold"]=("Урон холодом","Cold dmg"),
        ["DamageLight"]=("Урон молнией","Lightning dmg"),
        ["DamageChaos"]=("Урон хаосом","Chaos dmg"),
        ["BuildEdit"]=("Правка билда","Edit build"),
        ["BuildAscendancy"]=("Восхождение","Ascendancy"),
        ["BuildLevel"]=("Уровень","Level"),
        ["ProgressStageLabel"]=("Этап игры","Progress stage"),
        ["BuildStageStarter"]=("Стартер","Starter"),
        ["BuildStageEndgame"]=("Эндгейм","Endgame"),
        ["GameVersionLabel"]=("Версия игры","Game version"),
        ["ProgressStageHint"]=("«Стартер» — сопротивления считаются как есть; «эндгейм» — из каждого сопротивления вычитается 40 (штраф кампаний после Акта 3, до конца игры).","Starter counts resistances as-is; endgame subtracts 40 from each resistance (campaign penalty after Act 3)."),
        ["DialogueOk"]=("Готово","Done"),
        ["DialogueCancel"]=("Отмена","Cancel"),
        ["ImportCodeTitle"]=("Импорт билда","Import build"),
        ["ImportFileTitle"]=("Открыть .build / JSON","Open .build / JSON"),
        ["ImportIntro"]=("Код Path of Building декодируется локально. JSON — официальный формат Build Planner версии 1 (файл .build, экспорт poe.ninja). Загрузка по ссылке выполняется один раз, только по нажатию «Импортировать».","PoB codes decode locally. JSON is the official Build Planner v1 format (.build file, poe.ninja export). A link is fetched once, only when you press Import."),
        ["ImportTabPob"]=("Код PoB","PoB code"),
        ["ImportTabJson"]=("JSON / ссылка","JSON / link"),
        ["ImportPobHint"]=("Строка-код обмена из Path of Building (base64url).","The share string from Path of Building (base64url)."),
        ["ImportUrlLabel"]=("Ссылка на билд (например, экспорт poe.ninja)","Build link (e.g. a poe.ninja export URL)"),
        ["ImportJsonLabel"]=("Текст JSON (экспорт poe.ninja или содержимое файла .build)","JSON text (poe.ninja export or a .build file's contents)"),
        ["ImportGo"]=("Импортировать","Import"),
        ["ImportPobBad"]=("Код не декодируется.","The code does not decode."),
        ["ImportUrlBad"]=("Ссылка должна начинаться с http:// или https://","The link must start with http:// or https://"),
        ["ImportFetchFailed"]=("Скачивание не удалось:","Download failed:"),
        ["ImportNeither"]=("Строка не распознана ни как JSON, ни как код PoB.","The text is neither JSON nor a PoB code."),
        ["ImportNothing"]=("Введите код, JSON или ссылку.","Enter a code, JSON or a link."),
        ["ExchangeFilter"]=("Билды (*.build;*.json)|*.build;*.json|Все файлы (*.*)|*.*","Builds (*.build;*.json)|*.build;*.json|All files (*.*)|*.*"),
        ["PlannerFilter"]=("Файл билд-планировщика (*.build)|*.build","Build Planner file (*.build)|*.build"),
        ["ImportDialogTitle"]=("Открыть файл билда","Open build file"),
        ["ExportBuild"]=("Экспорт .build","Export .build"),
        ["ExportDone"]=("Экспортировано: {0}","Exported: {0}"),
        ["ImportFailed"]=("Импорт не удался:","Import failed:"),
        ["ImportReport"]=("Импорт завершён.\nПассивы: найдено {0}, не найдено {1} (узлы восхождения: {2}).\nУмения: активных {3}, поддержек {4}, нераспознанных камней {5}.\nСнаряжение перенесено: {6} предметов (самоцветов {7}, уников {8}); нераспознанных строк модов: {9}.","Import finished.\nPassives: matched {0}, unknown {1} (ascendancy nodes: {2}).\nSkills: {3} active, {4} supports, {5} unrecognized gems.\nEquipment transferred: {6} items (jewels {7}, uniques {8}); unrecognized mod lines: {9}."),
        ["ImportUnknownList"]=("Нераспознанные идентификаторы ({0} из полного списка):","Unrecognized ids ({0} of the full list):"),
        ["NewStarted"]=("Создан билд: {0}","Build created: {0}"),
        ["OpenedStatus"]=("Открыт билд: {0}","Build opened: {0}"),
        ["SupportGems"]=("Поддержки","Supports"),
        ["GemSearch"]=("Поиск умений…","Search skills…"),
        ["SupportSearch"]=("Поиск поддержек…","Search supports…"),
        ["GemLevel"]=("Ур.","Lvl"), ["GemQuality"]=("Кач.","Qual"),
        ["AddSupport"]=("Добавить","Add"),
        ["SupportsCount"]=("Поддержки: {0} / 5","Supports: {0} / 5"),
        ["RecommendedSupports"]=("Рекомендации каталога — подсказка, не проверка","Catalog recommendations — a hint, not validation"),
        ["DeleteGroupQuestion"]=("Удалить группу умений?","Delete this skill group?"),
        ["ResetSkillsQuestion"]=("Очистить все группы умений? Действие можно отменить.","Clear all skill groups? This can be undone."),
        ["NoGroups"]=("Групп пока нет — создай первую.","No groups yet — create the first one."),
        ["Character"]=("Персонаж","Character"),
        ["IconsNotice"]=("Иконки предметов и камней — арт из Path of Exile 2 (© GGG, из публичных зеркал; см. NOTICE.txt). Соответствие патчу не зафиксировано.","Item and gem icons use Path of Exile 2 artwork (© GGG, via public mirrors; see NOTICE.txt). Patch parity is not pinned."),
        ["QualityNote"]=("Влияние качества на числа пока не рассчитывается: подтверждённая формула не подключена.","Quality does not affect numbers yet: no verified formula is connected."),
        ["SocketsHint"]=("Пустое гнездо — выбор поддержки. Крестик на заполненном — убрать.","Click an empty socket to pick a support. The small × removes a socketed gem."),
        ["RemoveSupport"]=("Убрать поддержку","Remove support"),
        ["SupportPickerTitle"]=("Камень поддержки","Support gem"),
        ["SupportPickerHint"]=("Поддержки из этой группы уже исключены из списка. Совместимость не проверяется — правила игры шире каталога.","Supports already in this group are hidden. Compatibility is not validated — game rules are broader than the catalog."),
        ["PickSupport"]=("Выбрать","Pick"),
        ["DpsPerSecond"]=("Урон/с:","DPS:"),
        ["CharacterSheet"]=("— экран персонажа (расчёты v1)","— character sheet (v1 calculations)"),
        ["LevelUp"]=("Уровень +1","Level +1"), ["LevelDown"]=("Уровень −1","Level −1"),
        ["Resources"]=("РЕСУРСЫ","RESOURCES"),
        ["CharLife"]=("Жизнь","Life"), ["CharMana"]=("Мана","Mana"), ["CharEnergyShield"]=("Энергетический щит","Energy Shield"),
        ["CharSpirit"]=("Дух","Spirit"),
        ["Defences"]=("ЗАЩИТА","DEFENCE"),
        ["CharArmour"]=("Броня","Armour"), ["CharEvasion"]=("Уклонение","Evasion"), ["CharAccuracy"]=("Точность","Accuracy"),
        ["CharHitChance"]=("Шанс попадания","Hit chance"), ["CharMonsterHitChance"]=("Шанс попадания монстра","Monster hit chance"),
        ["CharBlock"]=("Шанс блока атаки","Attack block chance"), ["CharSpellBlock"]=("Шанс блока заклинаний","Spell block chance"), ["CharSuppression"]=("Подавление заклинаний","Spell suppression"), ["CharDeflection"]=("Шанс отклонения","Deflection chance"),
        ["CharMoveSpeed"]=("Скорость передвижения","Movement speed"), ["CharLifeRegen"]=("Восстановление жизни","Life regen"),
        ["EhpPhysical"]=("EHP: физический удар","EHP: physical hit"), ["EhpExpectedAttack"]=("EHP: средняя атака монстра","EHP: expected monster attack"), ["EhpFire"]=("EHP: огонь","EHP: fire"),
        ["EhpCold"]=("EHP: холод","EHP: cold"), ["EhpLightning"]=("EHP: молния","EHP: lightning"), ["EhpChaos"]=("EHP: хаос","EHP: chaos"),
        ["EhpNote"]=("оценка против стандартного монстра {0} ур., размер удара {1}; успешный удар, эффективный raw pool {2}. Для хаоса ЭЩ получает двойной урон. Без учёта шанса попадания, блока, отклонения и восстановления.","estimate vs level-{0} default monster, hit size {1}; successful hit, effective raw pool {2}. Chaos deals double damage to ES. Hit chance, block, deflection and recovery excluded."),
        ["ExpectedEhpNote"]=("средняя атака: hit chance {0}%, block {1}%, deflection {2}%; blocked hit считается с 0% damage, deflected hit предотвращает 40%. Это physical-only estimate.","expected attack: hit chance {0}%, block {1}%, deflection {2}%; blocked hit uses 0% damage, deflected hit prevents 40%. Physical-only estimate."),
        ["Attributes"]=("ХАРАКТЕРИСТИКИ","ATTRIBUTES"),
        ["AttrStrength"]=("Сила","Strength"), ["AttrDexterity"]=("Ловкость","Dexterity"), ["AttrIntelligence"]=("Интеллект","Intelligence"),
        ["Resistances"]=("СОПРОТИВЛЕНИЯ","RESISTANCES"),
        ["ResFire"]=("Огонь","Fire"), ["ResCold"]=("Холод","Cold"), ["ResLightning"]=("Молния","Lightning"), ["ResChaos"]=("Хаос","Chaos"),
        ["ResMax"]=("кап {0}%","cap {0}%"),
        ["PerLevelShort"]=("за уровень","per level"), ["PerPoint"]=("за 1 пункт","per point"), ["PerSecondShort"]=("в секунду","per second"),
        ["PerStrengthShort"]=("за силу","per Str"), ["PerDexterityShort"]=("за ловкость","per Dex"), ["PerIntelligenceShort"]=("за интеллект","per Int"),
        ["EsRecharge"]=("восстановление {0} в секунду; старт через {1} с без урона по Щиту (без модели прерывания)","recharge {0}/s; starts after {1}s without ES damage (no interruption state)"),
        ["ArmourEstimate"]=("≈ −{0}% урона от удара монстра {1} ур. (A/(A+12·урон))","≈ −{0}% from a level-{1} monster hit (A/(A+12·dmg))"),
        ["EvasionNote"]=("рейтинг; шансы показаны против стандартного монстра уровня персонажа","rating; chances are shown against a same-level default monster"),
        ["HitChanceNote"]=("против стандартного монстра {0} ур.","against a level-{0} default monster"),
        ["MonsterHitChanceNote"]=("стандартный монстр {0} ур. против вашего уклонения","level-{0} default monster against your evasion"),
        ["BlockNote"]=("атака; максимум {0}% по текущему PoB2 reference","attack; maximum {0}% from the current PoB2 reference"),
        ["SpellBlockNote"]=("заклинания; максимум {0}%; последствия блока пока не входят в EHP","spells; maximum {0}%; block consequences are not included in EHP yet"),
        ["SuppressionNote"]=("{0}% шанс; подавляется {1}% spell damage; пока не включено в EHP","{0}% chance; prevents {1}% of spell damage; not included in EHP yet"),
        ["DeflectionNote"]=("рейтинг {0}; отклонённый удар предотвращает {1}% урона; шанс — против точности стандартного монстра","rating {0}; a deflected hit prevents {1}% damage; chance is against the default monster accuracy"),
        ["SkillDamage"]=("УРОН УМЕНИЙ","SKILL DAMAGE"),
        ["KindAttack"]=("атака","attack"), ["KindSpell"]=("заклинание","spell"), ["KindSpirit"]=("дух","spirit"), ["KindOther"]=("умение","skill"),
        ["DpsCrit"]=("крит:","crit:"),
        ["DpsAvgHit"]=("средний удар:","avg hit:"), ["DpsMana"]=("мана:","mana:"),
        ["DpsUnit"]=("расчётный урон в секунду","estimated damage per second"),
        ["NoSkillsYet"]=("Групп умений пока нет. Создай их на странице «Умения».","No skill groups yet. Create them on the Skills page."),
        ["UnaccountedHeader"]=("НЕ УЧТЕНО: {0} статов","UNACCOUNTED: {0} stats"),
        ["UnaccountedNote"]=("Условные и особые эффекты не входят в расчёт v1. Полный список: Data/Game/unresolved-tree-lines.txt.","Conditional and special effects are outside v1. Full list: Data/Game/unresolved-tree-lines.txt."),
        ["Assumptions"]=("ДОПУЩЕНИЯ И ИСТОЧНИКИ","ASSUMPTIONS AND SOURCES"),
        ["AssumptionLevel"]=("Уровень: +12 жизни, +4 маны, +6 точности, +3 уклонения за уровень (maxroll Defence Guide, 18.09.2026).","Level: +12 life, +4 mana, +6 accuracy, +3 evasion per level (maxroll Defence Guide, 2026-09-18)."),
        ["AssumptionAttributes"]=("Сила +2 жизни, Ловкость +5 точности, Интеллект +2 маны (poe2.dev, 0.5.x).","Strength +2 life, Dexterity +5 accuracy, Intelligence +2 mana (poe2.dev, 0.5.x)."),
        ["AssumptionCrit"]=("Базовый бонус крит. урона 100% (крит = 2×). Крит атак — от оружия, заклинаний — от камня.","Base Critical Damage Bonus 100% (crit = 2x). Attack crit from the weapon, spell crit from the gem."),
        ["AssumptionArmour"]=("Броня: −урон = A/(A+12·удар), не более 90%; оценка против монстра уровня персонажа (данные RePoE default_monster_stats).","Armour: DR = A/(A+12·hit), capped 90%; estimated against a same-level default monster (RePoE default_monster_stats)."),
        ["AssumptionBlock"]=("Блок атаки: базовый максимум 50%, дополнительные максимумы и override, общий cap 90%; spell block и последствия блокированного удара не считаются.","Attack block: 50% base maximum, maximum additions and override, 90% global cap; spell block and blocked-hit consequences are not calculated."),
        ["AssumptionSuppression"]=("Подавление заклинаний: chance cap 100%, базовый effect 50%; отображается только при наличии source stat и пока не входит в EHP.","Spell suppression: 100% chance cap, 50% base effect; shown only when a source stat exists and not included in EHP yet."),
        ["AssumptionDeflection"]=("Отклонение: шанс по формуле PoB2 против точности стандартного монстра, cap 95%; отклонённый hit предотвращает базовые 40% урона. Entropy и сценарии не считаются.","Deflection: PoB2 chance formula against default-monster accuracy, capped at 95%; a deflected hit prevents the baseline 40% damage. Entropy and scenarios are not modeled."),
        ["AssumptionEsRecharge"]=("Восстановление Щита: базовые 12,5%/с и старт через 4 с; модификаторы скорости учитываются. Окно после последнего урона доступно как bounded helper; состояния боя и active reservation context пока не моделируются.","ES recharge: base 12.5%/s and 4s start delay; recharge-speed modifiers are applied. A bounded post-damage window helper exists; combat state and active reservation context are not modeled yet."),
        ["AssumptionHitChance"]=("Шанс попадания — формулы PoB2 rating-vs-rating с округлением и капом 5–100%; это оценка против стандартного монстра того же уровня. Поведение границ и патчевые детали требуют fixture/runtime проверки.","Hit chance uses PoB2 rating-vs-rating formulas with rounding and a 5–100% cap; this is a same-level default-monster estimate. Boundary and patch-specific behavior still require fixture/runtime verification."),
        ["AssumptionEhp"]=("EHP — вектор по типам урона для одного успешного удара стандартного монстра того же уровня: physical/elemental используют Жизнь + ЭЩ, хаос — Жизнь + половину ЭЩ из-за двойного урона по ЭЩ. Без шанса попадания, блока, отклонения, подавления, восстановления, пробития/экспозиции и явных bypass-модификаторов.","EHP is a damage-type vector for one successful same-level default-monster hit: physical/elemental use Life + ES, chaos uses Life + half ES because chaos deals double damage to ES. Hit chance, block, deflection, suppression, recovery, penetration/exposure and explicit bypass modifiers are excluded."),
        ["AssumptionRes"]=("Сопротивления — эффективный результат = базовая линия этапа + сырые источники дерева/снаряжения/самоцветов, с верхним капом; их вклад показан рядом с каждой строкой.","Resistances show the effective result: stage baseline + raw tree/gear/jewel sources, with an upper cap; source contribution is listed beside each row."),
        ["AssumptionSupports"]=("Поддержки НЕ изменяют расчётный урон (их мультипликаторы — отдельный этап).","Supports do NOT modify calculated damage yet (their multipliers are a later stage)."),
        ["AssumptionConversion"]=("Внутренние конверсии урона умений не применяются; «получить как» учтено для атак.","In-skill damage conversion is not applied; 'gain as' is counted for attacks."),
        ["AssumptionQuality"]=("Качество предметов пока не меняет числа.","Item quality does not change numbers yet."),
        ["CharacterCalcFailed"]=("Расчёт временно недоступен: ошибка вычисления (записана в журнал). Билд не изменён.","Calculations are temporarily unavailable: an evaluation error was journalled. The build is unchanged."),
        ["CharacterDataNotice"]=("Расчёты v1 по закреплённым данным (RePoE 4.5.5.2, дерево GGG 0.5.5, карты статов). Русские игровые тексты не подключены — имена предметов и камней EN.","v1 calculations over pinned data (RePoE 4.5.5.2, GGG 0.5.5 tree, stat maps). Russian game text is not connected — item and gem names remain EN."),
        ["ItemCorrupted"]=("Осквернён","Corrupted"),
        ["CorruptedHint"]=("Осквернение заменяет Implicit одним особым модом из пула базы (данные RePoE, вид corrupted). Обратимой операции нет.","Corruption replaces the implicit with one special mod from the base's pool (RePoE 'corrupted' data). Not reversible."),
        ["CorruptAdd"]=("Осквернить","Corrupt"),
        ["RemoveMod"]=("Убрать модификатор","Remove modifier"),
        ["RemoveAugment"]=("Убрать вставку","Remove socketable"),
        ["LevelFromItems"]=("+{0} ур. от предметов","+{0} levels from items"),
        ["ProgressStage"]=("Прогресс кампании","Campaign progress"),
        ["StageStarter"]=("Стартер","Starter"),
        ["StageEndgame"]=("Эндгейм","Endgame"),
        ["StageHint"]=("Стартер: сопротивления стартуют с 0%. Эндгейм: после кампании каждая стихия имеет −40% (по −10% за акт); хаос не штрафуется.","Starter: resistances start at 0%. Endgame: after the campaign each element sits at −40% (−10% per act); Chaos is not penalised."),
        ["AssumptionResEndgame"]=("Сопротивления: кап 75% (до 90% максимумами); выбран «Эндгейм» — Огонь/Холод/Молния стартуют с −40% (−10% за акт кампании; хаос не штрафуется).","Resistances: 75% cap (up to 90% via maximums); Endgame selected — Fire/Cold/Lightning start at −40% (−10% per campaign act; Chaos not penalised)."),
        ["NoteDisabledGroup"]=("группа выключена","group disabled"),
        ["NoteSupportsExcluded"]=("поддержки не входят в расчёт","supports excluded from math"),
        ["NoteSupportsApplied"]=("поддержки учтены в расчёте","supports included in math"),
        ["NoteSupportsPartial"]=("часть поддержек без чисел в закреплённом источнике — не учтена","some supports lack pinned numbers — excluded"),
        ["NoteSupportFinalApprox"]=("множитель «только к максимуму урона» применён ко всему удару (приближение помечено)","maximum-only damage multiplier applied to the whole hit (labelled approximation)"),
        ["ResFromSources"]=("от дерева и снаряжения: {0}","from tree and gear: {0}"),
        ["RarityUnique"]=("Уникальный","Unique"),
        ["Jewels"]=("Самоцветы","Jewels"),
        ["JewelList"]=("Самоцветы в билде","Jewels in this build"),
        ["JewelCreate"]=("Создать самоцвет","Create jewel"),
        ["JewelEditor"]=("Редактор самоцвета","Jewel editor"),
        ["JewelFreeSockets"]=("Свободные гнёзда дерева (аллоцированные)","Free tree sockets (allocated)"),
        ["JewelFilledSockets"]=("Занятые гнёзда","Socketed"),
        ["JewelInsert"]=("Вставить в гнездо","Socket jewel"),
        ["JewelRemove"]=("Вынуть","Unsocket"),
        ["JewelSocketHint"]=("Гнездо появляется в списке, когда аллоцирован узел-гнездо на вкладке «Дерево» (1 очко).","A socket appears here once its jewel-socket node is allocated on the Tree tab (1 point)."),
        ["JewelSocketFailed"]=("Не удалось вставить: узел не является аллоцированным гнездом.","Could not socket: not an allocated jewel socket."),
        ["JewelUnnamed"]=("Безымянный самоцвет","Unnamed jewel"),
        ["JewelUniquePick"]=("Уник-самоцвет (из каталога)","Unique jewel (from catalog)"),
        ["JewelUniquePickHint"]=("Поиск по закреплённому списку уникальных самоцветов","Search the pinned list of unique jewels"),
        ["JewelUniqueNotesHint"]=("Закреплённый каталог не содержит модификаторов уников — впиши их текст из игры в поле заметок вручную.","The pinned catalog has no unique modifiers — enter their text from the game manually in the notes field."),
        ["JewelBaseNote"]=("Базы самоцветов (Алмаз, Рубин, Сапфир, Изумруд) в закреплённом каталоге баз отсутствуют, поэтому самоцвет хранится без базы — как в импорте PoB.","Jewel bases (Diamond, Ruby, Sapphire, Emerald) are absent from the pinned base list, so a jewel is stored baseless — same as the PoB import."),
        ["JewelRadiusNote"]=("Честное ограничение: аффиксы «в радиусе» (JewelRadius…) пока не влияют на расчёт — нужна модель подсчёта узлов в радиусе; остальные аффиксы самоцветов действуют глобально.","Honest limit: radius affixes (JewelRadius…) do not affect the math yet — a counted-radius model is required; other jewel affixes act globally."),
        ["TreeSocketLabel"]=("Гнездо #{0}","Socket #{0}"),
        ["QualityNoteShort"]=("Качество указано, но на расчёт пока не влияет (формула не подключена).","Quality is recorded but does not affect the math yet (no verified formula)."),
        ["UniquePick"]=("Уник (поиск)","Unique (search)"),
        ["UniquePickHint"]=("Выбор из закреплённого списка уников: подставит имя и редкость «Уникальный»","Pick from the pinned unique list: fills the name and the Unique rarity"),
        ["UniqueNotesHint"]=("Уник: впиши модификаторы из игры — закреплённый каталог не содержит их текстов.","Unique: enter its modifiers from the game — the pinned catalog has no unique text."),
        ["JewelNoBase"]=("самоцвет · базы нет в закреплённом каталоге","jewel · base missing from the pinned catalog"),
        ["GemMetaActive"]=("Активное умение · Уровень {0} · Качество: {1}%","Active skill · Level {0} · Quality: {1}%"),
        ["GemMetaSupport"]=("Камень поддержки · Уровень {0} · Качество: {1}%","Support gem · Level {0} · Quality: {1}%"),
        ["NoteWrongWeaponSet"]=("не соответствует набору оружия","does not match the weapon set"),
        ["NoteNoGemData"]=("нет поуровневых данных умения","no per-level skill data"),
        ["NoteNoWeapon"]=("нужно оружие в активном наборе","requires a weapon in the active set"),
        ["NoteNoDamageStats"]=("в данных умения нет урона","no damage values in skill data")
    };
}
