using System.Globalization;
using System.Text;

namespace PoeBuilder.Core.Filters;

/// <summary>
/// Writes the plain-text filter file Path of Exile 2 reads.
/// <para>
/// The file is line-based and indentation-significant: <c>Show</c> or <c>Hide</c> starts a block, every
/// indented line under it is part of that block, and the game stops a block at the next unindented
/// <c>Show</c>/<c>Hide</c>. Nothing here is invented: each line is one field the client already parses.
/// </para>
/// <para>
/// Order is the player's order. The client takes the first block that matches an item, so moving a rule up
/// changes what the rules below it ever see — and the writer preserves the order rather than sorting it.
/// </para>
/// </summary>
public static class FilterWriter
{
    private const string Indent = "    ";

    /// <summary>The whole file, ready to be written next to the game's other filters.</summary>
    public static string Write(LootFilterDocument filter)
    {
        FilterValidation.Validate(filter);
        var text = new StringBuilder();
        // The header the client reads first: the game it is for, and the minimap switch the player set.
        text.AppendLine($"# {filter.Name}");
        text.AppendLine($"# Generated by PoeBuilder — game: {filter.Game}");
        text.AppendLine();
        // The game's own preamble. It is marked as the settings block so the reader can tell it apart from a
        // rule: an empty Show block here is not a mistake, it is the document's own header. The client reads the
        // keyword, not the comment, so the marker costs nothing.
        text.AppendLine("Show # settings");
        // -1 is how the game's own file switches the minimap off; the icon name after it is required even so.
        var marker = filter.Minimap ? 0 : -1;
        text.AppendLine(Indent + $"MinimapIcon {marker} White Circle");
        text.AppendLine(Indent + $"DropLevel {filter.DropLevel}");
        text.AppendLine();
        foreach (var block in filter.Blocks) WriteBlock(text, block);
        return text.ToString();
    }

    private static void WriteBlock(StringBuilder text, FilterBlock block)
    {
        // A parked rule keeps its place in the file but is commented out, which is exactly what the game reads
        // as "ignore": the order of the rules below it does not shift under the player's feet.
        // The kind is written in the game's own spelling — "Show", "Hide" — not shouted.
        var head = $"{block.Kind} # {block.Comment}".TrimEnd();
        text.AppendLine(block.Disabled ? "# " + head : head);
        foreach (var line in Lines(block)) text.AppendLine(block.Disabled ? "#" + Indent + line : Indent + line);
        text.AppendLine();
    }

    /// <summary>One block's own lines: its conditions first, then its style. Both are read in any order by the
    /// client, but conditions-then-style is what a hand-written filter looks like and what a player reads.</summary>
    public static IEnumerable<string> Lines(FilterBlock block)
    {
        foreach (var condition in block.Conditions)
        {
            if (FilterCondition.IsFlag(condition.Keyword)) { yield return condition.Keyword; continue; }
            if (FilterCondition.IsTextual(condition.Keyword)) { yield return $"{condition.Keyword} \"{condition.Value}\""; continue; }
            if (condition.IsRange) { yield return $"{condition.Keyword} {condition.Min} {condition.Max}"; continue; }
            yield return $"{condition.Keyword} {condition.Value}";
        }
        var style = block.Style;
        if (style.FontColor is { } font) yield return $"FontColor {Channel(font)}";
        if (style.BorderColor is { } border) yield return $"BorderColor {Channel(border)}";
        if (style.FontSize is { } size) yield return $"FontSize {size}";
        if (style.BorderWidth is { } width && width > 0) yield return $"BorderWidth {width}";
        if (style.Sound is { Length: > 0 } sound) yield return $"Sound \"{sound}\"";
        if (style.EnableFlare) yield return "EnableFlare";
        if (style.EnableGrey) yield return "EnableGrey";
        if (style.MinimapIcon is { } icon && FilterStyle.IsMinimapIcon(icon))
            yield return $"MinimapIcon {icon} {style.MinimapIconName ?? FilterStyle.MinimapIcons[icon]}";
    }

    private static string Channel(int[] color) =>
        string.Join(' ', color.Take(4).Select(c => c.ToString(CultureInfo.InvariantCulture)));
}
